---
sidebar: sidebar 
permalink: create-postgresql-server.html 
keywords: create, server, PostgreSQL, deploy, host, deploy a database host, database host 
summary: Creare un nuovo server SQL PostgreSQL in NetApp Workload Factory per database. 
---
= Creare un server PostgreSQL in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Per creare un nuovo server PostgreSQL o un host di database in NetApp Workload Factory for Databases è necessario un'implementazione del file system FSx for ONTAP e risorse per Active Directory.



== A proposito di questa attività

Prima di creare un server PostgreSQL da Workload Factory, informati sui tipi di distribuzione dello storage disponibili per la configurazione dell'host del database, sulle modalità operative di Workload Factory e sui requisiti per completare questa operazione.

.FSX per implementazioni di file system ONTAP
La creazione di un nuovo server PostgreSQL richiede un file system FSX per ONTAP come backend dello storage. Puoi usare un file system FSX for ONTAP esistente o creare un nuovo file system. Se selezioni un file system FSX per ONTAP esistente come back-end dello storage del database server, creiamo una nuova macchina virtuale di storage per i workload PostgreSQL.

+ I file system FSx per ONTAP hanno due modelli di distribuzione del server PostgreSQL: _Alta disponibilità (HA)_ o _singola istanza_.  A seconda del modello di distribuzione FSx for ONTAP selezionato, vengono create risorse diverse per il file system FSx for ONTAP .

* *Distribuzione ad alta disponibilità (ha)*: Viene implementato un file system FSX per NetApp ONTAP con più zone di disponibilità quando viene selezionato un nuovo file system FSX per ONTAP per la distribuzione ha. Volumi e LUN separati vengono creati per i file di dati, log e tempdb per un'implementazione HA. Vengono creati un volume e un LUN aggiuntivi per Quorum o disco di controllo per il cluster Windows. L'installazione HA configura la replica Streaming tra i server PostgreSQL primario e secondario.
* *Distribuzione a istanza singola*: Quando viene creato un nuovo server PostgreSQL, viene creato un file system FSX per ONTAP. Inoltre, vengono creati volumi e LUN separati per i file di dati, log e tempdb.




== Prima di iniziare

Devi avere link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["concedere i permessi di creazione dell'host del database"^] nel tuo account AWS per creare un nuovo host del database in Workload Factory.



== Creare un server PostgreSQL

È possibile utilizzare le modalità di distribuzione _creazione rapida_ o _creazione avanzata_ per completare questa attività in fabbrica dei carichi di lavoro con autorizzazioni _automatizza_. Puoi anche utilizzare i seguenti tool disponibili in Codebox: API REST, interfaccia a riga di comando di AWS, AWS CloudFormation e Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Scopri come utilizzare Codebox per l'automazione"^].


NOTE: Quando si utilizza Terraform da Codebox, il codice che si copia o si scarica nasconde `fsxadmin` e `vsadmin` password. Sarà necessario immettere nuovamente le password quando si esegue il codice. È necessario includere le seguenti autorizzazioni per l'account utente oltre alle autorizzazioni in modalità _automatizza_: `iam:TagRole` E `iam:TagInstanceProfile`. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#use-terraform-from-codebox["Scopri come utilizzare Terraform da Codebox"^].

[role="tabbed-block"]
====
.Creazione rapida
--

NOTE: In _Quick create_, HA è il modello di distribuzione predefinito, Windows 2016 è la versione predefinita di Windows e SQL 2019 Standard Edition è la versione predefinita di SQL.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Database, seleziona *Distribuisci host* e poi seleziona *PostgreSQL Server* dal menu.
. Selezionare *creazione rapida*.
. In *zona di atterraggio*, specificare quanto segue:
+
.. *Credenziali AWS*: Selezionare le credenziali AWS con autorizzazioni automatiche per implementare il nuovo host del database.
+
Le credenziali AWS con autorizzazioni di lettura/scrittura consentono a Workload Factory di distribuire e gestire il nuovo host del database dal tuo account AWS all'interno di Workload Factory.

+
Le credenziali AWS con autorizzazioni di _sola lettura_ consentono a Workload Factory di generare un modello CloudFormation da utilizzare nella console AWS CloudFormation.

+
Se non disponi delle credenziali AWS associate alla fabbrica dei carichi di lavoro e desideri creare il nuovo server nella fabbrica dei carichi di lavoro, segui *opzione 1* per andare alla pagina credenziali. Aggiungere manualmente le credenziali e le autorizzazioni richieste per la modalità _lettura/scrittura_ per i carichi di lavoro del database.

+
Se si desidera completare il modulo di creazione di un nuovo server in fabbrica del carico di lavoro in modo da poter scaricare un modello di file YAML completo per la distribuzione in AWS CloudFormation, seguire *opzione 2* per assicurarsi di disporre delle autorizzazioni necessarie per creare il nuovo server in AWS CloudFormation. Aggiungere manualmente le credenziali e le autorizzazioni richieste per la modalità di _sola lettura_ per i carichi di lavoro del database.

+
In alternativa, è possibile scaricare un modello di file YAML parzialmente completato dalla Codebox per creare lo stack al di fuori della fabbrica del carico di lavoro senza credenziali o autorizzazioni. Selezionare *CloudFormation* dal menu a discesa nel Codebox per scaricare il file YAML.

.. *Regione e VPC*: Selezionare una regione e una rete VPC.
+
Garantire che i gruppi di protezione per un endpoint dell'interfaccia esistente consentano l'accesso al protocollo HTTPS (443) alle subnet selezionate.

+
Endpoint dell'interfaccia del servizio AWS (SQS, FSX, EC2, CloudWatch, CloudFormation, SSM) e l'endpoint del gateway S3 vengono creati durante la distribuzione se non vengono trovati.

+
Gli attributi DNS VPC `EnableDnsSupport` e `EnableDnsHostnames` sono stati modificati per abilitare la risoluzione degli indirizzi degli endpoint se non sono già impostati su `true`.

.. *Zone di disponibilità*: Selezionare zone di disponibilità e subnet.
+

NOTE: Le implementazioni HA sono supportate solo nelle configurazioni FSX for ONTAP con più zone di disponibilità (MAZ).

+
Le sottoreti non devono condividere la stessa tabella di routing per la disponibilità elevata.

+
... Nel campo *Configurazione cluster - nodo 1*, selezionare l'area di disponibilità primaria per la configurazione MAZ FSX per ONTAP dal menu a discesa *zona di disponibilità* e una subnet dall'area di disponibilità primaria dal menu a discesa *sottorete*.
... Nel campo *Configurazione cluster - nodo 2*, selezionare l'area di disponibilità secondaria per la configurazione MAZ FSX per ONTAP dal menu a discesa *zona di disponibilità* e una subnet dall'area di disponibilità secondaria dal menu a discesa *sottorete*.




. In *Impostazioni applicazione*, immettere un nome utente e una password per *credenziali database*.
. In *connettività*, selezionare una coppia di chiavi per connettersi in modo sicuro all'istanza.
. In *Impostazioni infrastruttura*, fornire quanto segue:
+
.. *FSX per ONTAP system*: Creare un nuovo file system FSX per ONTAP o utilizzare un file system FSX per ONTAP esistente.
+
... *Crea nuovo file FSX per ONTAP*: Inserisci nome utente e password.
+
Un nuovo file system FSX per ONTAP può aggiungere 30 minuti o più di tempo di installazione.

... *Selezionare un file FSX esistente per ONTAP*: Selezionare FSX per nome ONTAP dal menu a discesa e immettere un nome utente e una password per il file system.
+
Per i file system FSX for ONTAP esistenti, verificare quanto segue:

+
**** Il gruppo di routing collegato a FSX per ONTAP consente di utilizzare i percorsi verso le sottoreti per la distribuzione.
**** Il gruppo di protezione consente il traffico proveniente dalle subnet utilizzate per la distribuzione, in particolare dalle porte TCP HTTPS (443) e iSCSI (3260).




.. *Dimensione unità dati*: Immettere la capacità dell'unità dati e selezionare l'unità di capacità.


. Riepilogo:
+
.. *Anteprima predefinita*: Esaminare le configurazioni predefinite impostate da creazione rapida.
.. *Costo stimato*: Fornisce una stima degli addebiti che potrebbero essere sostenuti se sono state distribuite le risorse visualizzate.


. Fare clic su *Create* (Crea).
+
In alternativa, se si desidera modificare subito una di queste impostazioni predefinite, creare il server database con creazione avanzata.

+
È inoltre possibile selezionare *Salva configurazione* per distribuire l'host in un secondo momento.



--
.Creazione avanzata
--
.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nel riquadro Database, seleziona *Distribuisci host* e poi seleziona *PostgreSQL Server* dal menu.
. Selezionare *creazione avanzata*.
. In *modello di distribuzione*, selezionare *istanza standalone* o *alta disponibilità (ha)*.
. In *zona di atterraggio*, specificare quanto segue:
+
.. *Credenziali AWS*: Selezionare le credenziali AWS con autorizzazioni automatiche per implementare il nuovo host del database.
+
Le credenziali AWS con autorizzazioni _automatizza_ consentono al workload di implementare e gestire in fabbrica il nuovo host del database dal tuo account AWS all'interno di una fabbrica di carichi di lavoro.

+
Le credenziali AWS con autorizzazioni di _sola lettura_ consentono a Workload Factory di generare un modello CloudFormation da utilizzare nella console AWS CloudFormation.

+
Se non disponi delle credenziali AWS associate alla fabbrica dei carichi di lavoro e desideri creare il nuovo server nella fabbrica dei carichi di lavoro, segui *opzione 1* per andare alla pagina credenziali. Aggiungere manualmente le credenziali e le autorizzazioni richieste per la modalità _lettura/scrittura_ per i carichi di lavoro del database.

+
Se si desidera completare il modulo di creazione di un nuovo server in fabbrica del carico di lavoro in modo da poter scaricare un modello di file YAML completo per la distribuzione in AWS CloudFormation, seguire *opzione 2* per assicurarsi di disporre delle autorizzazioni necessarie per creare il nuovo server in AWS CloudFormation. Aggiungere manualmente le credenziali e le autorizzazioni richieste per la modalità di _sola lettura_ per i carichi di lavoro del database.

+
In alternativa, è possibile scaricare un modello di file YAML parzialmente completato dalla Codebox per creare lo stack al di fuori della fabbrica del carico di lavoro senza credenziali o autorizzazioni. Selezionare *CloudFormation* dal menu a discesa nel Codebox per scaricare il file YAML.

.. *Regione e VPC*: Selezionare una regione e una rete VPC.
+
Garantire che i gruppi di protezione per un endpoint dell'interfaccia esistente consentano l'accesso al protocollo HTTPS (443) alle subnet selezionate.

+
Endpoint dell'interfaccia del servizio AWS (SQS, FSX, EC2, CloudWatch, Cloud Formation, SSM) e l'endpoint del gateway S3 vengono creati durante la distribuzione se non vengono trovati.

+
Gli attributi DNS del VPC `EnableDnsSupport` e `EnableDnsHostnames` sono stati modificati per abilitare la risoluzione degli indirizzi degli endpoint se non sono già impostati su `true`.

.. *Zone di disponibilità*: Selezionare zone di disponibilità e subnet.
+
*Per distribuzioni di istanze singole*

+
Nel campo *Configurazione cluster - nodo 1*, selezionare una zona di disponibilità dal menu a discesa *zona di disponibilità* e una sottorete dal menu a discesa *sottorete*.

+
*Per distribuzioni HA*

+
... Nel campo *Configurazione cluster - nodo 1*, selezionare l'area di disponibilità primaria per la configurazione MAZ FSX per ONTAP dal menu a discesa *zona di disponibilità* e una subnet dall'area di disponibilità primaria dal menu a discesa *sottorete*.
... Nel campo *Configurazione cluster - nodo 2*, selezionare l'area di disponibilità secondaria per la configurazione MAZ FSX per ONTAP dal menu a discesa *zona di disponibilità* e una subnet dall'area di disponibilità secondaria dal menu a discesa *sottorete*.


.. *Gruppo di protezione*: Selezionare un gruppo di protezione esistente o creare un nuovo gruppo di protezione.
+
Due gruppi di protezione vengono collegati ai nodi SQL (istanze EC2) durante la distribuzione del nuovo server.

+
... Viene creato un gruppo di protezione del carico di lavoro per consentire porte e protocolli richiesti per PostgreSQL.
... Per un nuovo file system FSX per ONTAP, viene creato un nuovo gruppo di protezione che viene allegato al nodo SQL. Per un file system FSX for ONTAP esistente, il gruppo di sicurezza ad esso associato viene aggiunto automaticamente al nodo PostgreSQL che consente la comunicazione con il file system.




. In *Impostazioni applicazione*, fornire quanto segue:
+
.. Selezionare *sistema operativo* dal menu a discesa.
.. Selezionare *PostgreSQL versione* dal menu a discesa.
.. *Nome server database*: Immettere il nome del cluster di database.
.. *Credenziali database*: Immettere un nome utente e una password per un nuovo account di servizio o utilizzare le credenziali di account di servizio esistenti in Active Directory.


. In *connettività*, selezionare una coppia di chiavi per connettersi in modo sicuro all'istanza.
. In *Impostazioni infrastruttura*, fornire quanto segue:
+
.. *DB Instance type*: Selezionare il tipo di istanza del database dal menu a discesa.
.. *FSX per ONTAP system*: Creare un nuovo file system FSX per ONTAP o utilizzare un file system FSX per ONTAP esistente.
+
... *Crea nuovo file FSX per ONTAP*: Inserisci nome utente e password.
+
Un nuovo file system FSX per ONTAP può aggiungere 30 minuti o più di tempo di installazione.

... *Selezionare un file FSX esistente per ONTAP*: Selezionare FSX per nome ONTAP dal menu a discesa e immettere un nome utente e una password per il file system.
+
Per i file system FSX for ONTAP esistenti, verificare quanto segue:

+
**** Il gruppo di routing collegato a FSX per ONTAP consente di utilizzare i percorsi verso le sottoreti per la distribuzione.
**** Il gruppo di protezione consente il traffico proveniente dalle subnet utilizzate per la distribuzione, in particolare dalle porte TCP HTTPS (443) e iSCSI (3260).




.. *Snapshot policy*: Attivato per impostazione predefinita. Le snapshot vengono acquisite giornalmente e hanno un periodo di conservazione di 7 giorni.
+
Gli snapshot vengono assegnati ai volumi creati per i carichi di lavoro PostgreSQL.

.. *Dimensione unità dati*: Immettere la capacità dell'unità dati e selezionare l'unità di capacità.
.. *IOPS forniti*: Selezionare *automatico* o *fornito dall'utente*. Se si seleziona *provisioning utente*, immettere il valore IOPS.
.. *Capacità di throughput*: Selezionare la capacità di throughput dal menu a discesa.
+
In alcune regioni, è possibile selezionare una capacità di 4 Gbps di throughput. Per fornire una capacità di throughput di 4 Gbps, il file system FSX per ONTAP deve essere configurato con un minimo di 5.120 GiB di capacità di storage SSD e 160.000 IOPS SSD.

.. *Crittografia*: Selezionare una chiave dal proprio account o una chiave da un altro account. È necessario immettere la chiave di crittografia ARN da un altro account.
+
Le chiavi di crittografia personalizzate di FSX per ONTAP non sono elencate in base all'applicabilità del servizio. Selezionare una chiave di crittografia FSX appropriata. Le chiavi di crittografia non FSX causeranno un errore nella creazione del server.

+
Le chiavi gestite da AWS vengono filtrate in base all'applicabilità del servizio.

.. *Tags*: Opzionalmente, è possibile aggiungere fino a 40 tag.
.. *Simple Notification Service*: In alternativa, è possibile attivare Simple Notification Service (SNS) per questa configurazione selezionando un argomento SNS per Microsoft SQL Server dal menu a discesa.
+
... Attivare il servizio di notifica semplice.
... Selezionare un ARN dal menu a discesa.


.. *Monitoraggio di CloudWatch*: Facoltativamente, è possibile attivare il monitoraggio di CloudWatch.
+
Si consiglia di abilitare CloudWatch per il debug in caso di errore. Gli eventi visualizzati nella console AWS CloudFormation sono di alto livello e non specificano la causa principale. Tutti i registri dettagliati vengono salvati nella `C:\cfn\logs` cartella nelle istanze EC2.

+
In CloudWatch, viene creato un gruppo di log con il nome dello stack. Un flusso di log per ogni nodo di convalida e nodo SQL viene visualizzato sotto il gruppo di log. CloudWatch mostra lo stato di avanzamento degli script e fornisce informazioni che aiutano a capire se e quando la distribuzione non riesce.

.. *Rollback delle risorse*: Questa funzione non è attualmente supportata.


. Riepilogo
+
.. *Costo stimato*: Fornisce una stima degli addebiti che potrebbero essere sostenuti se sono state distribuite le risorse visualizzate.


. Fare clic su *Crea* per distribuire il nuovo host del database.
+
In alternativa, è possibile salvare la configurazione.



--
====
.Cosa succederà
È possibile configurare manualmente gli utenti, l'accesso remoto e i database sul server PostgreSQL distribuito.
