---
sidebar: sidebar 
permalink: create-database.html 
keywords: create, database, creation, Microsoft SQL 
summary: Crea un database Microsoft SQL con NetApp Workload Factory per database. 
---
= Creare un database Microsoft SQL in NetApp Workload Factory per database
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La creazione di un nuovo database Microsoft SQL consente di gestire la risorsa all'interno di NetApp Workload Factory per database.

.A proposito di questa attività
Al momento della creazione del database, vengono creati due nuovi volumi nel file system FSX per ONTAP, che consiste di LUN indipendenti per ospitare i dati e i file di log per il database. I file di database del nuovo database sono dotati di thin provisioning e utilizzano solo pochi MB delle dimensioni totali allocate per il nuovo database.

Se si desidera separare lo storage per il database, è possibile farlo utilizzando un _punto di montaggio virtuale_. Il punto di montaggio virtuale consente di consolidare i database in poche unità comuni sull'host.

Per creare un database in Workload Factory sono necessarie le autorizzazioni di visualizzazione, pianificazione e analisi. In alternativa, è possibile copiare o scaricare un modello di codice parzialmente completato per completare l'operazione al di fuori della fabbrica del carico di lavoro. link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Scopri di più sulle autorizzazioni di Workload Factory"^] per decidere quale modalità desideri utilizzare.


NOTE: I server Microsoft SQL che utilizzano il protocollo SMB non supportano la creazione di database.

.Prima di iniziare
Prima di creare un nuovo database, assicurarsi di aver completato i seguenti prerequisiti.

* *Credenziali e permessi*: Devi avere link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Credenziali dell'account AWS e autorizzazioni di visualizzazione, pianificazione e analisi"^] per creare un nuovo database in Workload Factory.
+
In alternativa, è possibile utilizzare Codebox per copiare un modello in modo da poter distribuire un database al di fuori della fabbrica del carico di lavoro utilizzando l'API REST. link:https://docs.netapp.com/us-en/workload-setup-admin/codebox-automation.html["Ulteriori informazioni sull'automazione Codebox"^].

* *Host Windows*: se si utilizza la modalità _Creazione rapida_, è necessario disporre di un numero sufficiente di lettere di unità disponibili su Microsoft SQL Server per creare nuove unità per il nuovo database.
* *Microsoft SQL Server*: è necessario disporre di un Microsoft SQL Server gestito nella Workload Factory affinché i database ospitino il nuovo database.
* *AWS Systems Manager*: assicurarsi che `NT Authority\SYSTEM` i privilegi utente sono abilitati nell'host Microsoft SQL tramite AWS Systems Manager.




== Creare un database

È possibile utilizzare le modalità di distribuzione _Creazione rapida_ o _Creazione avanzata_ per completare questa attività in Workload Factory.

[role="tabbed-block"]
====
.Creazione rapida
--
.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella sezione Database, selezionare *Vai all'inventario dei database*.
. Dal menu Database, selezionare *Inventario*.
. Nell'inventario, seleziona *Microsoft SQL Server* come tipo di motore di database.
. Selezionare un server di database con un'istanza di SQL Server gestita in cui creare il database.
. Fare clic sul menu azioni dell'istanza gestita e quindi selezionare *Crea database utente*.
. Nella pagina Crea database utenti, in informazioni database, specificare quanto segue:
+
.. *Nome database*: Immettere il nome per il database.
.. *Fascicolazione*: Selezionare una fascicolazione per il database. È selezionata la fascicolazione predefinita SQL_Latin1_General_CP1_ci_AS" in Microsoft SQL Server.


. In Impostazioni file, specificare quanto segue:
+
.. *Modalità impostazioni file*: Selezionare *creazione rapida*.
.. *Nomi file e percorso*:
+
*** *Nome file di dati*: Immettere il nome del file di dati.
*** *Nome file di registro*: Immettere il nome del file di registro.


.. *Dimensioni file*: Immettere le dimensioni dei dati e del registro per il database.


. Fare clic su *Create* (Crea).
+
In alternativa, se si desidera modificare subito una di queste impostazioni predefinite, modificare la modalità *Impostazioni file* in *creazione avanzata*.



--
.Creazione avanzata
--
.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella sezione Database, selezionare *Vai all'inventario dei database*.
. Dal menu Database, selezionare *Inventario*.
. Nell'inventario, seleziona *Microsoft SQL Server* come tipo di motore di database.
. Selezionare un server di database con un'istanza di SQL Server gestita in cui creare il database.
. Fare clic sul menu azioni dell'istanza gestita e quindi selezionare *Crea database utente*.
. Selezionare *Crea database utenti*.
. Nella pagina Crea database utenti, in informazioni database, specificare quanto segue:
+
.. *Nome database*: Immettere il nome per il database.
.. *Fascicolazione*: Selezionare la fascicolazione per il database. È selezionata la fascicolazione predefinita SQL_Latin1_General_CP1_ci_AS" in Microsoft SQL Server.


. In Impostazioni file, specificare quanto segue:
+
.. *Modalità impostazioni file*: Selezionare *creazione avanzata*.
.. *Nomi file e percorso*:
+
... *File di dati*: Selezionare una lettera di unità e immettere il nome del file di dati.
+
In alternativa, fare clic sulla casella *punto di montaggio virtuale*.

... *File di registro*: Selezionare una lettera di unità e immettere il nome del file di registro.
+
In alternativa, fare clic sulla casella *punto di montaggio virtuale*.



.. *Dimensioni file*: Immettere le dimensioni dei dati e del registro per il database.


. Fare clic su *Create* (Crea).


--
====
Se è stato creato l'host del database, è possibile controllare l'avanzamento del lavoro nella scheda *monitoraggio processi*.
