---
sidebar: sidebar 
permalink: create-sandbox-clone.html 
keywords: create, clone, sandbox 
summary: Creare un clone sandbox in NetApp Workload Factory per database. 
---
= Creare un clone sandbox in NetApp Workload Factory per database
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La creazione di un clone sandbox di un database in NetApp Workload Factory for Databases consente di utilizzare il clone per sviluppo, test, integrazione, analisi, formazione, controllo qualità e altro ancora senza modificare il database di origine.

.A proposito di questa attività
Viene creato un clone sandbox a partire dallo snapshot più recente nel database di origine. Può essere clonato nello stesso Microsoft SQL Server del database di origine o in un altro Microsoft SQL Server, a condizione che condividano lo stesso file system FSX per ONTAP.

.Prima di iniziare
Prima di creare un clone sandbox, assicurarsi di aver completato i seguenti prerequisiti.

* *Credenziali e permessi*: Devi averelink:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Credenziali dell'account AWS e autorizzazioni in modalità _sola lettura_ o _lettura/scrittura_"^] per creare un clone sandbox in Workload Factory.
+
In alternativa, puoi utilizzare Codebox per copiare un modello parzialmente completato o creare un modello completo in modo da poter creare il clone sandbox al di fuori di Workload Factory utilizzando l'API REST. link:https://docs.netapp.com/us-en/workload-setup-admin/codebox-automation.html["Ulteriori informazioni sull'automazione Codebox"^] .

* *Microsoft SQL Server*: è necessario disporre di un Microsoft SQL Server gestito in Workload Factory per i database per ospitare il nuovo clone sandbox.
* *AWS Systems Manager*: assicurarsi che `NT Authority\SYSTEM` i privilegi utente sono abilitati nell'host Microsoft SQL tramite AWS Systems Manager.
* *Database di origine*: è necessario che sia disponibile un database di origine per il clone.


.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella sezione Database, selezionare *Vai all'inventario dei database*.
. In Database, selezionare la scheda *Sandbox*.
. Nella scheda Sandbox, selezionare *Crea nuova sandbox*.
. Nella pagina Crea nuova sandbox, in origine database, fornire quanto segue:
+
.. *Host del database di origine*: Selezionare l'host del database di origine.
.. *Istanza del database di origine*: Selezionare l'istanza del database di origine.
.. *Database di origine*: Selezionare il database di origine da cui eseguire la clonazione.


. In destinazione database, fornire quanto segue:
+
.. *Host database di destinazione*: Selezionare un host database di destinazione per il clone sandbox che si trova nello stesso VPC e che ha lo stesso file system FSX per ONTAP dell'host di origine.
.. *Istanza del database di destinazione*: Selezionare l'istanza del database di destinazione per il clone sandbox.
.. *Database di destinazione*: Immettere un nome per il clone sandbox.


. *Mount*: quando si clona un database SQL che contiene più file di dati e/o di registro, Workload Factory clona tutti i file sotto la lettera di unità assegnata automaticamente o definita.
+
Selezionare una delle seguenti opzioni:

+
.. *Assegnazione automatica del punto di montaggio*
.. *Definisci percorso punto di montaggio*
+
Fornire quanto segue per definire il percorso del punto di montaggio:

+
*** Immettere la lettera dell'unità per il percorso del file di dati.
*** Immettere la lettera dell'unità per il percorso del file di registro.




. *Definisci tag*: Selezionare un tag per definire il clone sandbox.
. Fare clic su *Create* (Crea).


Per verificare l'avanzamento del processo, andare alla scheda *monitoraggio processo*.
