---
sidebar: sidebar 
permalink: create-postgresql-server.html 
keywords: create, server, PostgreSQL, deploy, host, deploy a database host, database host 
summary: 'Creare un nuovo server SQL PostgreSQL all"interno della factory del carico di lavoro BlueXP  per i database.' 
---
= Creare un server PostgreSQL in fabbrica carichi di lavoro BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La creazione di un nuovo server PostgreSQL, o host di database, nella fabbrica di carichi di lavoro BlueXP  per i database richiede la distribuzione di file system FSX per ONTAP e le risorse per Active Directory.

.A proposito di questa attività
Avrai bisogno delle credenziali dell'account AWS e delle autorizzazioni _automatizza_.

Prima di iniziare, è necessario conoscere i tipi di distribuzione dello storage disponibili per la configurazione dell'host del database, la distribuzione di Active Directory, le modalità operative della fabbrica del carico di lavoro e i requisiti per completare questa operazione.

FSX per implementazioni di file system ONTAP:: La creazione di un nuovo server PostgreSQL richiede un file system FSX per ONTAP come backend dello storage. Puoi usare un file system FSX for ONTAP esistente o creare un nuovo file system. Se selezioni un file system FSX per ONTAP esistente come back-end dello storage del database server, creiamo una nuova macchina virtuale di storage per i workload PostgreSQL.


I file system FSX per ONTAP supportano le distribuzioni _standalone_ per PostgreSQL. Workload Factory crea un file system FSX per ONTAP in una singola zona di disponibilità, oltre a volumi e LUN separati per i file di dati, log e tempdb.

Modalità operative di fabbrica del carico di lavoro:: Workload Factory offre tre modalità operative che dipendono dalla comodità di lasciare che le risorse AWS vengano gestite in fabbrica dai carichi di lavoro.


Modalità *_Basic_*: In questa modalità operativa, non è necessario associare le credenziali dell'account AWS in fabbrica dei workload. È possibile copiare o scaricare un modello YAML parzialmente compilato dalla Codebox per completarlo al di fuori della fabbrica del carico di lavoro.

Modalità *_Read_*: In questa modalità operativa, fornisci le credenziali dell'account AWS con autorizzazioni di lettura che ti consentono di completare il modulo _Quick create_ o _Advanced create_ e di copiarlo o scaricarlo. È anche possibile reindirizzare a CloudFormation da workload Factory con i dettagli del modulo completati. Inoltre, sarà possibile gestire il server di database installato in fabbrica dei workload.

*_Automate_ mode*: In questa modalità operativa, fornisci credenziali di account AWS con autorizzazioni automatiche che ti consentono di creare e gestire risorse AWS all'interno di workload factory.

.Prima di iniziare
Prima di creare un nuovo host di database, accertarsi di disporre dei seguenti prerequisiti.

Credenziali e autorizzazioni:: È necessario link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Credenziali dell'account AWS e automatizzare i permessi della modalità"^]creare un nuovo host di database in workload factory.
+
--
In alternativa, puoi utilizzare Codebox per copiare un modello vuoto o creare un modello completo in modo da implementare un database al di fuori della fabbrica di workload utilizzando API REST, AWS CLI o AWS CloudFormation. link:https://docs.netapp.com/us-en/workload-setup-admin/codebox-automation.html["Ulteriori informazioni sull'automazione Codebox"^].

--




== Creare un server di database

È possibile utilizzare le modalità di distribuzione _creazione rapida_ o _creazione avanzata_ per completare questa attività in fabbrica dei carichi di lavoro con autorizzazioni _automatizza_. È inoltre possibile utilizzare i seguenti strumenti disponibili in Codebox: API REST e CloudFormation. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Scopri come utilizzare Codebox per l'automazione"^].

+

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella sezione Database, selezionare *Deploy database host*, quindi selezionare *PostgreSQL* dal menu a discesa.
. Selezionare *creazione avanzata*.
. Per *modello di distribuzione*, *istanza standalone* è l'impostazione predefinita.
. In *Impostazioni AWS*, fornire quanto segue:
+
.. *Credenziali AWS*: Selezionare le credenziali AWS con autorizzazioni automatiche per implementare il nuovo host del database.
+
Le credenziali AWS con autorizzazioni _automatizza_ consentono al workload di implementare e gestire in fabbrica il nuovo host del database dal tuo account AWS all'interno di una fabbrica di carichi di lavoro.

+
Le credenziali AWS con autorizzazioni _Read_ consentono ai workload di generare un modello CloudFormation da utilizzare nella console AWS CloudFormation.

+
Se non disponi delle credenziali AWS associate alla fabbrica dei carichi di lavoro e desideri creare il nuovo server nella fabbrica dei carichi di lavoro, segui *opzione 1* per andare alla pagina credenziali. Aggiungere manualmente le credenziali e le autorizzazioni necessarie per la modalità _automatizza_ per i carichi di lavoro del database.

+
Se si desidera completare il modulo di creazione di un nuovo server in fabbrica del carico di lavoro in modo da poter scaricare un modello di file YAML completo per la distribuzione in AWS CloudFormation, seguire *opzione 2* per assicurarsi di disporre delle autorizzazioni necessarie per creare il nuovo server in AWS CloudFormation. Aggiungere manualmente le credenziali e le autorizzazioni richieste per la modalità _Read_ per i carichi di lavoro del database.

+
In alternativa, è possibile scaricare un modello di file YAML parzialmente completato dalla Codebox per creare lo stack al di fuori della fabbrica del carico di lavoro senza credenziali o autorizzazioni. Selezionare *CloudFormation* dal menu a discesa nel Codebox per scaricare il file YAML.

.. *Regione e VPC*: Selezionare una regione e una rete VPC.
+
Garantire che i gruppi di protezione per un endpoint dell'interfaccia esistente consentano l'accesso al protocollo HTTPS (443) alle subnet selezionate.

+
Endpoint dell'interfaccia del servizio AWS (SQS, FSX, EC2, CloudWatch, Cloud Formation, SSM) e l'endpoint del gateway S3 vengono creati durante la distribuzione se non vengono trovati.

+
Gli attributi DNS del VPC `EnableDnsSupport` e `EnableDnsHostnames` sono stati modificati per abilitare la risoluzione degli indirizzi degli endpoint se non sono già impostati su `true`.

.. *Zone di disponibilità*: Selezionare zone di disponibilità e subnet.
+
Per implementazioni a singola istanza::
+
--
... Nel campo *Configurazione cluster - nodo 1*, selezionare una zona di disponibilità dal menu a discesa *zona di disponibilità* e una sottorete dal menu a discesa *sottorete*.


--


.. *Gruppo di protezione*: Selezionare un gruppo di protezione esistente o creare un nuovo gruppo di protezione.
+
Due gruppi di protezione vengono collegati ai nodi SQL (istanze EC2) durante la distribuzione del nuovo server.

+
... Viene creato un gruppo di protezione del carico di lavoro per consentire porte e protocolli richiesti per PostgreSQL.
... Per un file system FSX for ONTAP esistente, il gruppo di sicurezza ad esso associato viene aggiunto automaticamente al nodo PostgreSQL che consente la comunicazione con il file system. Quando viene creato un nuovo sistema FSX per ONTAP, viene creato un nuovo gruppo di protezione per il file system FSX per ONTAP e lo stesso gruppo di protezione viene collegato anche al nodo SQL.




. In *Impostazioni applicazione*, fornire quanto segue:
+
.. Selezionare *sistema operativo* dal menu a discesa.
.. Selezionare *PostgreSQL versione* dal menu a discesa.
.. *Nome server database*: Immettere il nome del cluster di database.
.. *Credenziali database*: Immettere un nome utente e una password per un nuovo account di servizio o utilizzare le credenziali di account di servizio esistenti in Active Directory.


. In *connettività*, selezionare una coppia di chiavi per connettersi in modo sicuro all'istanza.
. In *Impostazioni infrastruttura*, fornire quanto segue:
+
.. *DB Instance type*: Selezionare il tipo di istanza del database dal menu a discesa.
.. *FSX per ONTAP system*: Creare un nuovo file system FSX per ONTAP o utilizzare un file system FSX per ONTAP esistente.
+
... *Crea nuovo file FSX per ONTAP*: Inserisci nome utente e password.
+
Un nuovo file system FSX per ONTAP può aggiungere 30 minuti o più di tempo di installazione.

... *Selezionare un file FSX esistente per ONTAP*: Selezionare FSX per nome ONTAP dal menu a discesa e immettere un nome utente e una password per il file system.
+
Per i file system FSX for ONTAP esistenti, verificare quanto segue:

+
**** Il gruppo di routing collegato a FSX per ONTAP consente di utilizzare i percorsi verso le sottoreti per la distribuzione.
**** Il gruppo di protezione consente il traffico proveniente dalle subnet utilizzate per la distribuzione, in particolare dalle porte TCP HTTPS (443) e iSCSI (3260).




.. *Snapshot policy*: Attivato per impostazione predefinita. Le snapshot vengono acquisite giornalmente e hanno un periodo di conservazione di 7 giorni.
+
Gli snapshot vengono assegnati ai volumi creati per i carichi di lavoro PostgreSQL.

.. *Dimensione unità dati*: Immettere la capacità dell'unità dati e selezionare l'unità di capacità.
.. *IOPS forniti*: Selezionare *automatico* o *fornito dall'utente*. Se si seleziona *provisioning utente*, immettere il valore IOPS.
.. *Capacità di throughput*: Selezionare la capacità di throughput dal menu a discesa.
+
In alcune regioni, è possibile selezionare una capacità di 4 Gbps di throughput. Per fornire una capacità di throughput di 4 Gbps, il file system FSX per ONTAP deve essere configurato con un minimo di 5.120 GiB di capacità di storage SSD e 160.000 IOPS SSD.

.. *Crittografia*: Selezionare una chiave dal proprio account o una chiave da un altro account. È necessario immettere la chiave di crittografia ARN da un altro account.
+
Le chiavi di crittografia personalizzate di FSX per ONTAP non sono elencate in base all'applicabilità del servizio. Selezionare una chiave di crittografia FSX appropriata. Le chiavi di crittografia non FSX causeranno un errore nella creazione del server.

+
Le chiavi gestite da AWS vengono filtrate in base all'applicabilità del servizio.

.. *Tags*: Opzionalmente, è possibile aggiungere fino a 40 tag.
.. *Simple Notification Service*: In alternativa, è possibile attivare Simple Notification Service (SNS) per questa configurazione selezionando un argomento SNS per Microsoft SQL Server dal menu a discesa.
+
... Attivare il servizio di notifica semplice.
... Selezionare un ARN dal menu a discesa.


.. *Monitoraggio di CloudWatch*: Facoltativamente, è possibile attivare il monitoraggio di CloudWatch.
+
Si consiglia di abilitare CloudWatch per il debug in caso di errore. Gli eventi visualizzati nella console AWS CloudFormation sono di alto livello e non specificano la causa principale. Tutti i registri dettagliati vengono salvati nella `C:\cfn\logs` cartella nelle istanze EC2.

+
In CloudWatch, viene creato un gruppo di log con il nome dello stack. Un flusso di log per ogni nodo di convalida e nodo SQL viene visualizzato sotto il gruppo di log. CloudWatch mostra lo stato di avanzamento degli script e fornisce informazioni che aiutano a capire se e quando la distribuzione non riesce.

.. *Rollback delle risorse*: Questa funzione non è attualmente supportata.


. Riepilogo
+
.. *Costo stimato*: Fornisce una stima degli addebiti che potrebbero essere sostenuti se sono state distribuite le risorse visualizzate.


. Fare clic su *Crea* per distribuire il nuovo host del database.
+
In alternativa, è possibile salvare la configurazione.



.Cosa succederà
Ora è possibile link:create-database.html["Creare un database in una fabbrica di carichi di lavoro BlueXP  per i database"].
