---
sidebar: sidebar 
permalink: detect-host.html 
keywords: detect, detect server instance, instance, detect a database host, instance 
summary: 'Rilevamento di un"istanza di Microsoft SQL Server in una farm di workload BlueXP  per i database.' 
---
= Rilevamento di un'istanza di Microsoft SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Rilevamento di un'istanza di Microsoft SQL Server in una farm di workload BlueXP  per i database.

Questa attività serve a rilevare un'istanza _non rilevata_.

.A proposito di questa attività
Quando le credenziali AWS sono associate alla fabbrica dei carichi di lavoro, i database consentono il rilevamento automatico di Microsoft SQL Server a partire da SQL Server 2016 con i seguenti tipi di storage AWS:

* FSX per ONTAP
* Memorizzazione di blocchi elastici (EBS)
* FSX per Windows file Server


Nei database, le istanze rilevate sono classificate come segue:

* _Istanze non rilevate_: Istanze non rilevate che sono state rilevate automaticamente dalla fabbrica del carico di lavoro. Le istanze non vengono rilevate nei seguenti casi:
+
** L'autenticazione di Microsoft SQL Server non riesce.
** Il file system FSX per ONTAP per Microsoft SQL Server non è registrato con il tuo account in fabbrica di workload.


* _Istanze non gestite_: Istanze rilevate che non sono gestite da workload Factory
* _Istanze gestite_: Istanze rilevate gestite da workload Factory


Il primo passo per gestire un'istanza di Microsoft SQL Server, o istanza host, nella factory del carico di lavoro per i database è il rilevamento di un'istanza del server di database non rilevata.

.Prima di iniziare
I requisiti per il rilevamento di un'istanza del server di database non rilevata sono i seguenti:

* È necessario link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Credenziali dell'account AWS"^]rilevare un'istanza del server di database in workload factory.
* Il tipo di archiviazione per l'istanza deve essere uno dei seguenti:
+
** FSX per ONTAP
** Memorizzazione di blocchi elastici (EBS)
** FSX per Windows file Server


* Le istanze EC2 devono avere un profilo ruolo/istanza che consenta la connessione SSM per il rilevamento.
+
Quando viene rilevata un'istanza di Microsoft SQL, l'ambiente esistente non viene modificato. Il rilevamento avviene attraverso AWS Systems Manager Session Manager (SSM). Senza il profilo di istanza IAM corretto, il rilevamento non riesce. link:https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-troubleshooting.html["Ulteriori informazioni sulla risoluzione dei problemi di SSM"^].



.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella sezione Database, selezionare *Vai all'inventario dei database*.
. In Database, selezionare la scheda *inventario*.
. Fare clic sulla freccia dell'elenco a discesa per espandere la riga dell'host da rilevare.
+
L'host si espande e vengono visualizzate le istanze dell'host.

. Fare clic sul menu a tre punti dell'istanza da rilevare.
. Fare clic su *rileva*.
. Nella finestra di dialogo *rileva istanza*, specificare il nome utente e la password di Microsoft SQL Server o FSX per il nome utente e la password di ONTAP.
+
Workload Factory convalida le credenziali Microsoft SQL o FSX per le credenziali ONTAP.

+
Se una di queste credenziali non è disponibile, workload Factory tenta di installare il `aws.tools.SimpleSystemsManagement` modulo in PowerShell.

. Fare clic su *rileva*.
+
Vengono visualizzate le informazioni sull'istanza rilevata.

. Selezionare *Sì, Gestisci istanza tramite workload Factory* o *No*.
. Fare clic su *fine*.


.Cosa succederà
Quando il tipo di archiviazione per l'istanza host è FSX per ONTAP, è possibile link:manage-server.html["gestire l'istanza tramite workload factory"].
