---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, databases 
summary: Le limitazioni note identificano piattaforme, dispositivi o funzioni non supportate da questa versione del prodotto o che non interagiscono correttamente con esso. Esaminare attentamente queste limitazioni. 
---
= Limitazioni note
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le limitazioni note identificano piattaforme, dispositivi o funzioni non supportate da questa versione del prodotto o che non interagiscono correttamente con esso. Esaminare attentamente queste limitazioni.



== Supporto della versione dell'immagine AMI

Vengono visualizzate solo quattro versioni recenti o revisioni di immagini AMI per ciascuna versione SQL. Non è consentita l'installazione da un'immagine AMI precedente alle ultime quattro versioni.



== AMI personalizzato

La distribuzione con un AMI personalizzato presuppone che nell'immagine siano presenti supporti di installazione. Ciò è necessario per la configurazione FCI per i seguenti motivi:

* Per disinstallare e riconfigurare per formare il cluster FCI
* Quando si seleziona una fascicolazione diversa da quella impostata nell'immagine per la distribuzione autonoma


Durante l'implementazione, workload Factory non installa un AMI personalizzato con più istanze di Microsoft SQL Server. Solo l'istanza predefinita di Microsoft SQL Server è selezionata e configurata come parte della distribuzione.



== Eseguire il rollback e riprovare per le distribuzioni non riuscite

Il rollback e il nuovo tentativo per le distribuzioni non riuscite non sono supportati in workload Factory. È possibile eseguire il rollback o riprovare uno stack non riuscito dalla console CloudFormation in AWS.



== Active Directory e rollback delle risorse DNS

Le seguenti risorse DNS non vengono rimosse da Active Directory e DNS quando si esegue il rollback di un test o di una distribuzione non riuscita dalla console CloudFormation in AWS:

* Ciascun nodo della distribuzione SQL al relativo indirizzo IP di gestione
* Nome cluster di Windows agli indirizzi IP secondari riservati di istanze EC2 nei casi di FCI
* Nome FCI SQL per i due indirizzi IP riservati da entrambe le istanze EC2 in FCI


Sarà necessario ripulire manualmente questi elementi o attendere che il dominio elimini le voci obsolete.



== Supporto di configurazione per gruppi di disponibilità sempre attivo

La gestione delle configurazioni dei gruppi di disponibilità sempre attive non è supportata in workload Factory.



== Gruppi di protezione Active Directory gestiti dagli utenti

Se si seleziona "Active Directory gestito dall'utente" durante la distribuzione di Microsoft SQL Server in workload Factory, è necessario fornire un gruppo di protezione che consenta la distribuzione del traffico tra le EC2 istanze al servizio directory. Workload Factory non collega automaticamente il gruppo di sicurezza per Active Directory gestito dall'utente come per AWS Managed Microsoft ad.



== Chiavi di crittografia personalizzate

Le chiavi di crittografia personalizzate per FSX for ONTAP non sono elencate in base all'applicabilità del servizio. È necessario scegliere la chiave appropriata. Le chiavi gestite da AWS vengono filtrate in base all'applicabilità al servizio.



== Modello CloudFormation

Un modello CloudFormation (file YAML) generato da Codebox scaricato o copiato ha un periodo di conservazione limitato di sette giorni.



== Supporto sandbox

Il numero massimo di cloni sandbox che è possibile creare da un server di database è 90.



== Rilevamento e gestione di Microsoft SQL Server

Il rilevamento di Microsoft SQL Server non è stato salvato. Ogni volta che accedi ai database in workload Factory, il rilevamento di Microsoft SQL Server viene eseguito nuovamente per identificare le installazioni SQL nell'area.



== Scopri i risparmi

Nella scheda inventario, il costo stimato mostrato per ogni istanza di Microsoft SQL viene calcolato a livello di file system FSX per ONTAP e non per i volumi che ospitano l'istanza SQL.



== File system FSX multipli per ONTAP

Workload Factory non supporta la creazione o il salvataggio di configurazioni per Microsoft SQL Server con più file system FSX per ONTAP. È supportata solo una distribuzione della configurazione del file system FSX per ONTAP.



== Disponibilità regionale per la distribuzione di Microsoft SQL Server in una rete privata con Terraform

La distribuzione di Microsoft SQL Server in una rete privata senza connettività in uscita mediante Terraform è supportata solo nell'area geografica US-East-1 (N. Virginia).
