---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, databases 
summary: Le limitazioni note identificano piattaforme, dispositivi o funzioni non supportate da questa versione del prodotto o che non interagiscono correttamente con esso. Esaminare attentamente queste limitazioni. 
---
= Limitazioni note per la farm di workload BlueXP  per i database
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le limitazioni note identificano piattaforme, dispositivi o funzioni non supportate da questa versione del prodotto o che non interagiscono correttamente con esso. Esaminare attentamente queste limitazioni.



== Supporto della versione dell'immagine AMI

Vengono visualizzate solo quattro versioni recenti o revisioni di immagini AMI per ciascuna versione SQL. Non è consentita l'installazione da un'immagine AMI precedente alle ultime quattro versioni.



== AMI personalizzato

La distribuzione con un AMI personalizzato presuppone che nell'immagine siano presenti supporti di installazione. Ciò è necessario per la configurazione FCI per i seguenti motivi:

* Per disinstallare e riconfigurare per formare il cluster FCI
* Quando si seleziona una fascicolazione diversa da quella impostata nell'immagine per la distribuzione autonoma


Come parte della distribuzione, workload Factory non installa un AMI personalizzato con più istanze di Microsoft SQL Server. Solo l'istanza predefinita di Microsoft SQL Server è selezionata e configurata come parte della distribuzione.



== Eseguire il rollback e riprovare per le distribuzioni non riuscite

Il rollback e il nuovo tentativo per le distribuzioni non riuscite non sono supportati in fabbrica del carico di lavoro. È possibile eseguire il rollback o riprovare uno stack non riuscito dalla console CloudFormation in AWS.



== Active Directory e rollback delle risorse DNS

Le seguenti risorse DNS non vengono rimosse da Active Directory e DNS quando si esegue il rollback di un test o di una distribuzione non riuscita dalla console CloudFormation in AWS:

* Ciascun nodo della distribuzione SQL al relativo indirizzo IP di gestione
* Nome cluster di Windows agli indirizzi IP secondari riservati di istanze EC2 nei casi di FCI
* Nome FCI SQL per i due indirizzi IP riservati da entrambe le istanze EC2 in FCI


Sarà necessario ripulire manualmente questi elementi o attendere che il dominio elimini le voci obsolete.



== Supporto di configurazione per gruppi di disponibilità sempre attivo

La gestione delle configurazioni dei gruppi di disponibilità sempre attive non è supportata in fabbrica dei workload.



== Chiavi di crittografia personalizzate

Le chiavi di crittografia personalizzate per FSX for ONTAP non sono elencate in base all'applicabilità del servizio. È necessario scegliere la chiave appropriata. Le chiavi gestite da AWS vengono filtrate in base all'applicabilità al servizio.



== Modello CloudFormation

Un modello CloudFormation (file YAML) generato da Codebox scaricato o copiato ha un periodo di conservazione limitato di sette giorni.



== Supporto sandbox

Il numero massimo di cloni sandbox che è possibile creare da un server di database è 90.



== Rilevamento e gestione di Microsoft SQL Server

Il rilevamento di Microsoft SQL Server non è stato salvato. Ogni volta che si accede ai database nella fabbrica del carico di lavoro, il rilevamento di Microsoft SQL Server viene eseguito nuovamente per identificare le installazioni SQL nell'area.



== Scopri i risparmi

Nella scheda inventario, il costo stimato mostrato per ogni istanza di Microsoft SQL viene calcolato a livello di file system FSX per ONTAP e non per i volumi che ospitano l'istanza SQL.



== File system FSX multipli per ONTAP

Workload Factory non supporta la creazione o il salvataggio di configurazioni per Microsoft SQL Server con più file system FSX per ONTAP. È supportata solo una distribuzione della configurazione del file system FSX per ONTAP.



== Limiti di ottimizzazione



=== Ottimizzazione del corretto dimensionamento delle risorse di calcolo

Quando si passa a determinati tipi di istanza, è possibile reimpostare la configurazione di rete, che potrebbe causare un errore di connessione del nodo durante l'ottimizzazione e causare un errore del processo. Potrebbe essere necessario un intervento manuale per controllare e aggiornare le impostazioni DNS e le sessioni iSCSI. Per ulteriori informazioni sulle limitazioni di ridimensionamento di EC2, fare riferimento a link:https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/resize-limitations.html["Documentazione di Amazon Elastic Compute Cloud"^].



=== Ottimizzazione della configurazione ONTAP e del sistema operativo

L'ottimizzazione in blocco per più istanze di SQL Server non è supportata per la configurazione di ONTAP e la configurazione del sistema operativo.



=== Valutazione delle patch del sistema operativo per l'ottimizzazione

La valutazione delle patch del sistema operativo effettuata a scopo di ottimizzazione potrebbe non funzionare in una rete privata. La valutazione si basa su AWS Patch Manager. Per informazioni su come applicare patch alle istanze di Windows EC2 in una rete privata, fare riferimento a link:https://aws.amazon.com/blogs/mt/how-to-patch-windows-ec2-instances-in-private-subnets-using-aws-systems-manager/["AWS Cloud Operations Blog "come applicare patch alle istanze di Windows EC2 nelle subnet private usando AWS Systems Manager""^].



== Calcolo del risparmio on-premise

Non viene preso in considerazione il calcolo delle dimensioni del volume per lo storage on-premise di Microsoft SQL Server, né dei risparmi in percentuale e sui costi.



== Valutazione della replica tra aree

* La valutazione di ottimizzazione non può determinare se viene utilizzata la replica tra aree (CRR) quando il file system FSX for ONTAP di destinazione si trova in un account AWS diverso.
* Workload Factory valuta solo la configurazione CRR del file system di origine FSX per ONTAP.




== Numero di database all'interno delle istanze di SQL Server

Nella scheda inventario e nella dashboard, workload Factory supporta fino a 850 database nelle istanze di SQL Server.
