---
sidebar: sidebar 
permalink: learn-databases.html 
keywords: Databases 
summary: 'NetApp Workload Factory for Databases è un servizio di distribuzione e manutenzione di database end-to-end con best practice integrate per l"ottimizzazione, la clonazione automatica sottile e funzionalità di monitoraggio e risoluzione.' 
---
= Scopri di più su NetApp Workload Factory per database
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Databases è un servizio di distribuzione e manutenzione di database end-to-end con best practice integrate per l'ottimizzazione, la clonazione automatica sottile e funzionalità di monitoraggio e risoluzione.



== Che cos'è NetApp Workload Factory per database?

NetApp Workload Factory for Databases rileva, valuta, pianifica, esegue il provisioning e sposta i dati di Microsoft SQL Server nelle distribuzioni Amazon FSx for NetApp ONTAP (FSx for ONTAP), ottimizzate per soddisfare le aspettative in termini di prestazioni e costi, nel rispetto delle best practice del settore.  Durante l'intero ciclo di vita, NetApp Workload Factory for Databases garantisce ottimizzazione e gestione continue per i database su FSx per ONTAP.

Per ulteriori informazioni su Workload Factory, fare riferimento alink:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Panoramica di Workload Factory"^] .



== Vantaggi di Workload Factory per i database autogestiti

Workload Factory offre le seguenti utili best practice e automazioni per i database autogestiti.



=== Best practice

* Conoscenza integrata di AWS Cloud, Microsoft Windows e SQL Server e NetApp ONTAP per le implementazioni SQL Server su EC2 istanze.
* Costo totale di proprietà implementazione ottimizzata.
* Automazione dell'implementazione end-to-end basata sulle Best practice di AWS, Microsoft e ONTAP.
* La modalità di distribuzione _Creazione rapida_ ti aiuta a evitare potenziali insidie dovute alla configurazione manuale.




=== Automazione con Workload Factory Codebox

Workload Factory introduce l'automazione integrata con _Codebox_.  Codebox offre i seguenti vantaggi di automazione:

* *Generazione di frammenti di codice*: I frammenti di codice IAC (Infrastructure-as-Code) vengono generati durante la creazione delle risorse, consentendo una perfetta integrazione con i flussi di lavoro di orchestrazione esistenti.
* *Copilota dell'infrastruttura come codice*: Codebox è un copilota dell'infrastruttura come codice (IaC) che aiuta gli sviluppatori e i DevOps a generare codice per eseguire qualsiasi operazione supportata da Workload Factory.
* *Code Viewer e catalogo di automazione*: Il Codebox fornisce un visualizzatore di codice per una rapida analisi dell'automazione e un catalogo di automazione per un rapido riutilizzo futuro.




=== Funzionalità di Workload Factory per database

Workload Factory per database offre le seguenti funzionalità:

* *Implementazioni semplici e veloci*: Semplificate e ottimizzate la vostra esperienza di provisioning selezionando le risposte alle domande sulle specifiche ed eliminando il tempo generalmente richiesto per studiare come eseguire il provisioning e configurare Microsoft SQL Server su AWS.
* *Orchestrazione automatizzata*: disponibile tramite la console Workload Factory con modalità di distribuzione _Rapida_ e _Avanzata_, Chatbot e AWS CloudFormation tramite Codebox.
* *Funzioni integrate*: Utilizza le Best practice di NetApp, Microsoft e Amazon e le selezioni delle risorse AWS integrate nella configurazione dell'implementazione.
* *Stima dei costi*: Valutate i potenziali risparmi sui costi con il calcolatore di risparmio, che stima e fornisce dettagli sui costi dettagliati di storage, calcolo, licenze SQL, snapshot e clonazione per le implementazioni esistenti di Microsoft SQL Server con Elastic Block Store ed FSX per Windows file Server rispetto ad FSX per ONTAP.
* *Modelli di automazione riutilizzabili*: crea, riutilizza e personalizza i modelli CloudFormation dal Workload Factory Codebox per future distribuzioni di Microsoft SQL Server in più ambienti.
* *Rilevamento e provisioning delle risorse AWS*: Rileva automaticamente Microsoft SQL Server in FSX per ONTAP, FSX per Windows file Server e Elastic Block Store distribuito dal tuo account AWS. L'inventario dei database è un punto di lancio per esplorare le opportunità di risparmio sui costi per i server in altri sistemi storage AWS o uno strumento di gestione per FSX per le istanze e i server basati su ONTAP.
* *Creazione Sandbox*: Creare un ambiente di database isolato on-demand che possa essere utilizzato per test, integrazione, diagnostica e formazione, senza influire sui dati di produzione.
* *Creazione di database*: Creare un database utente per i server Microsoft SQL esistenti con le modalità _Quick_ o _Advanced_ create per configurare le regole di confronto del database, i nomi dei file e le dimensioni. Configurazione dello storage inclusa.
* *Monitoraggio processi*: Monitorare e tenere traccia dell'avanzamento dell'esecuzione dei processi del database e diagnosticare e risolvere i problemi in caso di errori.
* *Ottimizzazione continua*: Esegue la scansione continua del sistema Microsoft SQL Server offline, fornendo un report completo di informazioni, opportunità e consigli per raggiungere l'eccellenza operativa.




== Vantaggi di Amazon FSX per ONTAP per database a gestione autonoma

* *Durata, disponibilità e affidabilità*: FSX per ONTAP offre diverse funzionalità che migliorano la durata e la disponibilità dei database gestiti autonomamente ospitati su FSX per ONTAP, come l'alta disponibilità che supporta le distribuzioni di zone di disponibilità singole e multiple, le snapshot integrate con le applicazioni, il disaster recovery migliorato tramite la replica e il backup efficiente.
* *Prestazioni e scalabilità*: FSX per ONTAP offre ottimizzazione delle prestazioni con throughput elevato, bassa latenza, connessioni di rete ad alta velocità e scalabilità con più file system per scalare le prestazioni aggregate richieste per un carico di lavoro.
* *Efficienza e gestione dei dati*: FSX per ONTAP offre diverse funzionalità che migliorano l'efficienza e la gestione dei dati, ad esempio thin clone efficienti in termini di spazio, thin provisioning, compressione e deduplica, nonché tiering dei dati con accesso meno frequente nel pool di capacità.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/learn-fsx-ontap.html["Scopri di più su FSx per ONTAP per Workload Factory"^] .



=== Modalità operative in Workload Factory

Tre diverse modalità operative (base, sola lettura e lettura/scrittura) offrono opzioni flessibili per l'implementazione all'interno e all'esterno di Workload Factory. Ottieni un valore immediato con zero-trust in modalità _basic_ con frammenti di codice da utilizzare al di fuori di Workload Factory. Ottieni un valore incrementale con fiducia incrementale nelle modalità _sola lettura_ e _lettura/scrittura_.

Scopri di più su link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["modalità operative in Workload Factory"^] .



== Strumenti per utilizzare NetApp Workload Factory

È possibile utilizzare NetApp Workload Factory con i seguenti strumenti:

* *Console Workload Factory*: la console Workload Factory fornisce una visione visiva e olistica delle applicazioni e dei progetti.
* * NetApp Console*: la NetApp Console offre un'esperienza di interfaccia ibrida che consente di utilizzare Workload Factory insieme ad altri servizi dati NetApp .
* *Chiedimi*: utilizza l'assistente AI Chiedimi per porre domande e scoprire di più su Workload Factory senza uscire dalla console di Workload Factory. Accedi a Chiedimi dal menu della guida di Workload Factory.
* *CloudShell CLI*: Workload Factory include una CloudShell CLI per gestire e utilizzare gli ambienti AWS e NetApp su più account da un'unica CLI basata su browser. Accedi a CloudShell dalla barra superiore della console di Workload Factory.
* *API REST*: utilizza le API REST di Workload Factory per distribuire e gestire i tuoi file system FSx for ONTAP e altre risorse AWS.
* *CloudFormation*: utilizza il codice AWS CloudFormation per eseguire le azioni definite nella console Workload Factory per modellare, fornire e gestire risorse AWS e di terze parti dallo stack CloudFormation nel tuo account AWS.
* *Provider Terraform NetApp Workload Factory*: utilizza Terraform per creare e gestire i flussi di lavoro dell'infrastruttura generati nella console Workload Factory.




== Configurazioni supportate

Workload Factory supporta i seguenti motori di database, versioni, sistemi operativi e modelli di distribuzione in base alle best practice di AWS, NetApp ONTAP, Microsoft SQL Server, Oracle e PostgreSQL.

[cols="1,1,1,1"]
|===
| Motore | Versione | Sistema operativo | Modello di distribuzione 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2016 | FCI, istanza singola 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2016 | FCI, istanza singola 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2016 | FCI, istanza singola 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2019 | FCI, istanza singola 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2019 | FCI, istanza singola 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2019 | FCI, istanza singola 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2022 | FCI, istanza singola 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2022 | FCI, istanza singola 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2022 | FCI, istanza singola 


| Microsoft SQL Server | SQL Server 2017 | Qualunque | FCI, istanza singola 


| Microsoft SQL Server | SQL Server 2016, 2017, 2019, 2022 | Qualunque | FCI, istanza singola 


| Oracolo | 19c | RHEL, SuSe Linux | Autonomo (singolo/multi-tenant) 


| Oracolo | 21c | RHEL, SuSe Linux | Autonomo (singolo/multi-tenant) 


| Oracolo | 19c | RHEL, SuSe Linux | Autonomo (singolo/multi-tenant) 


| Oracolo | 21c | RHEL, SuSe Linux | Autonomo (singolo/multi-tenant) 


| Oracolo | 19c | RHEL, SuSe Linux | Standalone con ASM (tenant singolo/multiplo) 


| Oracolo | 21c | RHEL, SuSe Linux | Standalone con ASM (tenant singolo/multiplo) 


| PostgreSQL | PostgreSQL 15 | Amazon Linux 2023 AMI | HA, istanza autonoma 


| PostgreSQL | PostgreSQL 16 | Amazon Linux 2023 AMI | HA, istanza autonoma 
|===


== Servizi AWS integrati

I database includono i seguenti servizi AWS integrati:

* CloudFormation
* Servizio di notifica semplice
* CloudWatch
* Manager di sistema
* Gestore segreti




== Regioni

I database sono supportati in tutte le aree commerciali in cui è supportato FSX per ONTAP. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Visualizza le regioni Amazon supportate."^]

Le seguenti regioni AWS non sono supportate:

* Regioni della Cina
* Regioni di GovCloud (USA)
* Cloud segreto
* Cloud top secret




== Assistenza

Amazon FSX per NetApp ONTAP è una soluzione AWS first-party. Per domande o problemi di supporto tecnico associati al file system, all'infrastruttura o alla soluzione FSX per ONTAP che utilizza questo servizio, utilizza il Support Center nella console di gestione AWS per aprire un caso di supporto con AWS. Selezionare il servizio "FSX per ONTAP" e la categoria appropriata. Fornire le informazioni rimanenti necessarie per creare il caso di supporto AWS.

Per domande generali su Workload Factory o sulle applicazioni e i servizi di Workload Factory, fare riferimento alink:get-help.html["Ottieni assistenza per NetApp Workload Factory per database"] .
