---
sidebar: sidebar 
permalink: learn-databases.html 
keywords: Databases 
summary: 'NetApp Workload Factory for Databases è un servizio di distribuzione e manutenzione di database end-to-end con best practice integrate per l"ottimizzazione, la clonazione automatica sottile e funzionalità di monitoraggio e risoluzione.' 
---
= Scopri di più su NetApp Workload Factory per database
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for Databases è un servizio di distribuzione e manutenzione di database end-to-end con best practice integrate per l'ottimizzazione, la clonazione automatica sottile e funzionalità di monitoraggio e risoluzione.



== Che cos'è NetApp Workload Factory per database?

NetApp Workload Factory for Databases scopre, valuta, pianifica, fornisce e sposta i dati di Microsoft SQL Server, PostgreSQL e Oracle su implementazioni Amazon FSx for NetApp ONTAP (FSx for ONTAP) ottimizzate per soddisfare le tue aspettative di prestazioni e costi, rispettando le best practice del settore. NetApp Workload Factory for Databases ottimizza e gestisce continuamente i database su FSx for ONTAP.

Per ulteriori informazioni su Workload Factory, fare riferimento alink:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Panoramica di Workload Factory"^] .



== Vantaggi di Workload Factory per i database autogestiti

Workload Factory offre le migliori pratiche e l'automazione per i database autogestiti.



=== Best practice

* Conoscenza integrata di AWS Cloud, Microsoft Windows e SQL Server e NetApp ONTAP per le implementazioni SQL Server su EC2 istanze.
* Costo totale di proprietà implementazione ottimizzata.
* Automazione dell'implementazione end-to-end basata sulle Best practice di AWS, Microsoft e ONTAP.
* La modalità di distribuzione _Creazione rapida_ ti aiuta a evitare potenziali insidie dovute alla configurazione manuale.




=== Automazione con Workload Factory Codebox

Workload Factory introduce l'automazione integrata con _Codebox_.  Codebox offre i seguenti vantaggi di automazione:

* *Generazione di snippet di codice*: Workload Factory genera snippet di Infrastructure-as-Code (IaC) durante la creazione delle risorse, consentendo una perfetta integrazione con i flussi di lavoro di orchestrazione esistenti.
* *Copilota dell'infrastruttura come codice*: Codebox è un copilota dell'infrastruttura come codice (IaC) che aiuta gli sviluppatori e i DevOps a generare codice per eseguire qualsiasi operazione supportata da Workload Factory.
* *Code Viewer e catalogo di automazione*: Il Codebox fornisce un visualizzatore di codice per una rapida analisi dell'automazione e un catalogo di automazione per un rapido riutilizzo futuro.




=== Funzionalità di Workload Factory per database

Workload Factory per database offre le seguenti funzionalità:

* *Stima dei costi*: valuta i potenziali risparmi con il calcolatore di risparmi che stima e dettaglia i costi di risorse di storage, elaborazione, licenze SQL, snapshot e clonazione per le implementazioni esistenti di Microsoft SQL Server e Oracle con Elastic Block Store, FSx for Windows File Server e on-premises rispetto a FSx for ONTAP.
* *Implementazioni semplici e veloci*: semplifica e ottimizza il provisioning di host, database e sandbox con le best practice integrate di NetApp, Microsoft e Amazon che eliminano la complessità della configurazione manuale per le istanze di Microsoft SQL Server e PostgreSQL su AWS.
+
** È possibile effettuare il deployment dalla console di Workload Factory utilizzando le modalità di creazione _Rapida_ o _Avanzata_, oppure creare, riutilizzare e personalizzare i modelli AWS CloudFormation tramite Codebox per i deployment futuri in più ambienti.
** Crea database isolati su richiesta con configurazioni di storage e cloni sandbox utilizzabili per test, integrazione, diagnostica e formazione, senza influire sui dati di produzione.


* *Funzionalità di valutazione ben strutturata*: analizza continuamente i tuoi ambienti Microsoft SQL Server e Oracle per generare un report completo con approfondimenti, opportunità e raccomandazioni che ti aiuteranno a raggiungere l'eccellenza operativa, la sicurezza, l'affidabilità, l'efficienza delle prestazioni e l'ottimizzazione dei costi, in base alle best practice di AWS.
* *Analisi degli errori*: analizza e risolvi gli errori nei log con l'analizzatore AI per ottenere messaggi di errore dettagliati, passaggi per la risoluzione dei problemi e raccomandazioni per risolvere i problemi.
* *Gestione centralizzata*: gestisci le tue risorse Microsoft SQL Server, Oracle e PostgreSQL su FSx for ONTAP da un'unica posizione. In Workload Factory, visualizza l'infrastruttura collegata, gli account AWS, le credenziali, i file system FSx for ONTAP connessi, l'utilizzo delle risorse di storage inclusi i volumi NFS e le LUN iSCSI, lo stato di protezione, le prestazioni, lo stato di buona architettura e l'analisi degli errori.




== Vantaggi di Amazon FSX per ONTAP per database a gestione autonoma

* *Durata, disponibilità e affidabilità*: FSX per ONTAP offre diverse funzionalità che migliorano la durata e la disponibilità dei database gestiti autonomamente ospitati su FSX per ONTAP, come l'alta disponibilità che supporta le distribuzioni di zone di disponibilità singole e multiple, le snapshot integrate con le applicazioni, il disaster recovery migliorato tramite la replica e il backup efficiente.
* *Prestazioni e scalabilità*: FSX per ONTAP offre ottimizzazione delle prestazioni con throughput elevato, bassa latenza, connessioni di rete ad alta velocità e scalabilità con più file system per scalare le prestazioni aggregate richieste per un carico di lavoro.
* *Efficienza e gestione dei dati*: FSX per ONTAP offre diverse funzionalità che migliorano l'efficienza e la gestione dei dati, ad esempio thin clone efficienti in termini di spazio, thin provisioning, compressione e deduplica, nonché tiering dei dati con accesso meno frequente nel pool di capacità.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/learn-fsx-ontap.html["Scopri di più su FSx per ONTAP per Workload Factory"^] .



== Strumenti per utilizzare NetApp Workload Factory

È possibile utilizzare NetApp Workload Factory con i seguenti strumenti:

* *Console Workload Factory*: la console Workload Factory fornisce una visione visiva e olistica delle applicazioni e dei progetti.
* * NetApp Console*: la NetApp Console offre un'esperienza di interfaccia ibrida che consente di utilizzare Workload Factory insieme ad altri servizi dati NetApp .
* *Chiedimi*: utilizza l'assistente AI Chiedimi per porre domande e scoprire di più su Workload Factory senza uscire dalla console di Workload Factory. Accedi a Chiedimi dal menu della guida di Workload Factory.
* *CloudShell CLI*: Workload Factory include una CloudShell CLI per gestire e utilizzare gli ambienti AWS e NetApp su più account da un'unica CLI basata su browser. Accedi a CloudShell dalla barra superiore della console di Workload Factory.
* *API REST*: utilizza le API REST di Workload Factory per distribuire e gestire i tuoi file system FSx for ONTAP e altre risorse AWS.
* *CloudFormation*: utilizza il codice AWS CloudFormation per eseguire le azioni definite nella console Workload Factory per modellare, fornire e gestire risorse AWS e di terze parti dallo stack CloudFormation nel tuo account AWS.
* *Provider Terraform NetApp Workload Factory*: utilizza Terraform per creare e gestire i flussi di lavoro dell'infrastruttura generati nella console Workload Factory.




== Configurazioni supportate

È possibile utilizzare Workload Factory con i seguenti motori di database, versioni, sistemi operativi e modelli di implementazione, seguendo le best practice di AWS, NetApp ONTAP, Microsoft SQL Server, Oracle e PostgreSQL.

[cols="1,1,1,1"]
|===
| Motore | Versione | Sistema operativo | Modello di distribuzione 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2016 | FCI, autonomo 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2016 | FCI, autonomo 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2016 | FCI, autonomo 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2019 | FCI, autonomo 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2019 | FCI, autonomo 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2019 | FCI, autonomo 


| Microsoft SQL Server | SQL Server 2016 | Windows Server 2022 | FCI, autonomo 


| Microsoft SQL Server | SQL Server 2019 | Windows Server 2022 | FCI, autonomo 


| Microsoft SQL Server | SQL Server 2022 | Windows Server 2022 | FCI, autonomo 


| Microsoft SQL Server | SQL Server 2017 | Qualunque | FCI, autonomo 


| Microsoft SQL Server | SQL Server 2016, 2017, 2019, 2022 | Qualunque | FCI, autonomo 


| Microsoft SQL Server | SQL Server 2016, 2017, 2019, 2022 | Qualunque | Gruppo di disponibilità Always On 


| Oracolo | 19c | RHEL, SuSe Linux | Autonomo (singolo/multi-tenant) 


| Oracolo | 21c | RHEL, SuSe Linux | Autonomo (singolo/multi-tenant) 


| Oracolo | 19c | RHEL, SuSe Linux | Autonomo (singolo/multi-tenant) 


| Oracolo | 21c | RHEL, SuSe Linux | Autonomo (singolo/multi-tenant) 


| Oracolo | 19c | RHEL, SuSe Linux | Standalone con ASM (tenant singolo/multiplo) 


| Oracolo | 21c | RHEL, SuSe Linux | Standalone con ASM (tenant singolo/multiplo) 


| Oracolo | 19c, 21c | RHEL, SuSe Linux | Data Guard 


| PostgreSQL | PostgreSQL 15 | Amazon Linux 2023 AMI | HA, istanza autonoma 


| PostgreSQL | PostgreSQL 16 | Amazon Linux 2023 AMI | HA, istanza autonoma 
|===


== Servizi AWS integrati

I database includono i seguenti servizi AWS integrati:

* CloudFormation
* Servizio di notifica semplice
* CloudWatch
* Manager di sistema
* Gestore segreti




== Regioni

I database sono supportati in tutte le aree commerciali in cui è supportato FSX per ONTAP. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Visualizza le regioni Amazon supportate."^]

Le seguenti regioni AWS non sono supportate:

* Regioni della Cina
* Regioni di GovCloud (USA)
* Cloud segreto
* Cloud top secret




== Assistenza

Amazon FSX per NetApp ONTAP è una soluzione AWS first-party. Per domande o problemi di supporto tecnico associati al file system, all'infrastruttura o alla soluzione FSX per ONTAP che utilizza questo servizio, utilizza il Support Center nella console di gestione AWS per aprire un caso di supporto con AWS. Selezionare il servizio "FSX per ONTAP" e la categoria appropriata. Fornire le informazioni rimanenti necessarie per creare il caso di supporto AWS.

Per domande generali su Workload Factory o sulle applicazioni e i servizi di Workload Factory, fare riferimento alink:get-help.html["Ottieni assistenza per NetApp Workload Factory per database"] .
