---
sidebar: sidebar 
permalink: optimize-overview.html 
keywords: database configuration issues, issues, analyze, scan, optimize, improve, database configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations, storage, compute, application, resiliency, scan, optimization, SQL Server, host, instance 
summary: Workload Factory for Databases analizza regolarmente le configurazioni di Microsoft SQL Server e Oracle per determinare se ci sono problemi. 
---
= Analisi della configurazione per ambienti di database in Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory for Databases analizza regolarmente le configurazioni dei database per determinare se ci sono problemi con le distribuzioni di Microsoft SQL Server e Oracle su Amazon FSx for NetApp ONTAP .  Quando vengono rilevati problemi, Workload Factory ti mostra quali sono e ti spiega cosa è necessario modificare per garantire che le configurazioni del tuo database raggiungano le massime prestazioni, la massima efficienza dei costi e la conformità alle best practice.

Le funzionalità principali includono:

* Analisi quotidiana della configurazione
* Convalida automatica delle Best practice
* Consigli per un corretto dimensionamento
* Osservabilità proattiva
* Informazioni sull'azione
* Framework Advisor di AWS con architettura ottimale




== Componenti dell'analisi della configurazione

L'analisi della configurazione include i seguenti componenti:

Stato ben progettato:: Lo stato ben progettato si riferisce allo stato generale delle configurazioni del database; le configurazioni sono classificate come "ottimizzate", "non ottimizzate" o "con provisioning eccessivo". Lo stato ben progettato di una configurazione viene referenziato dall'interno di un'istanza di Microsoft SQL Server o di un database Oracle nella console di Workload Factory.
Punteggio ben strutturato:: Il punteggio include tutte le configurazioni attualmente analizzate e viene visualizzato come percentuale. Un punteggio del 25% significa che il 25% delle distribuzioni del database sono ben progettate. Il punteggio ben progettato è referenziato dalla schermata *Ben progettato* e da un'istanza di Microsoft SQL Server o da un database Oracle nella console Workload Factory.
Categorie di configurazione:: Le configurazioni sono organizzate nelle seguenti categorie: archiviazione, elaborazione, applicazione, resilienza e clonazione. Ogni categoria include valutazioni di configurazione specifiche che vengono analizzate regolarmente. Le categorie di configurazione sono referenziate dalla schermata *Ben architettata* e da un'istanza di Microsoft SQL Server o da un database Oracle nella console Workload Factory.




== Ambito di analisi

L'ambito dell'ottimizzazione è diverso a seconda del componente da valutare. Ad esempio, l'ottimizzazione dello storage avviene a livello di istanza SQL, mentre l'ottimizzazione del calcolo avviene a livello di host.



== Requisiti di analisi

Per un'analisi completa dell'ambiente del database, le risorse devono essere registrate e online.

link:register-instance.html["Scopri come registrare le risorse."]

.Cosa succederà
link:optimize-configurations.html["Implementare configurazioni di database ben progettate"]
