---
sidebar: sidebar 
permalink: optimize-configurations.html 
keywords: optimize, configuration, storage, compute, application, resiliency assessment, scan, optimization, Microsoft SQL Server, host, instance, FSx for ONTAP 
summary: 'Workload Factory per database analizza le configurazioni di Microsoft SQL Server, fornendo informazioni e consigli per aiutarti a raggiungere l"eccellenza operativa.' 
---
= Implementare configurazioni di database ben progettate nella fabbrica dei carichi di lavoro
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Utilizzando le informazioni e i suggerimenti dell'analisi della configurazione, sfrutta Workload Factory per implementare le best practice per le configurazioni del tuo database. È possibile esaminare facilmente lo stato di buona architettura, scoprire eventuali problemi con le configurazioni del database e intervenire per migliorare quelle non ottimizzate in termini di affidabilità, sicurezza, efficienza, prestazioni e costi.

link:optimize-overview.html["Scopri di più sull'analisi della configurazione e sullo stato ben progettato nella fabbrica dei carichi di lavoro."]

.A proposito di questa attività
Workload Factory analizza quotidianamente le configurazioni del database. L'analisi giornaliera fornisce informazioni sullo stato di progettazione, nonché approfondimenti e raccomandazioni con opzioni per risolvere automaticamente i problemi di configurazione in modo che le configurazioni soddisfino le best practice.

È possibile esaminare i suggerimenti per i problemi di configurazione e risolverli dall'inventario dei database nella console della Workload Factory.

Cosa viene analizzato:: Workload Factory analizza lo stato di corretta architettura delle seguenti configurazioni per le istanze di Microsoft SQL Server:
+
--
* Dimensionamento dello storage: Include Tier di storage, capacità aggiuntiva del file system, dimensioni dei dischi di log e dimensioni dei dischi TempDB
* Layout dello storage: Comprende posizionamento dei file di dati degli utenti, posizionamento dei file di log e posizionamento di TempDB
* Configurazione di archiviazione: include gestione della capacità, provisioning sottile, criteri di tiering, snapshot, stato Microsoft Multipath I/O (MPIO) e impostazione del timeout MPIO
* Calcolo: Include il dimensionamento corretto, le patch del sistema operativo e le impostazioni della scheda di rete come Receive Side Scaling (RSS) e TCP offload
* Applicazioni: Include le licenze di Microsoft SQL Server, la patch di Microsoft SQL Server e le impostazioni MAXDOP
* Resilienza: Include snapshot locali, FSX per i backup ONTAP e replica tra aree (CRR)
* Cloni: include opzioni per aggiornare ed eliminare i cloni (sandbox) creati all'interno o all'esterno della fabbrica dei carichi di lavoro e che hanno più di 60 giorni


--


.Prima di iniziare
* Devi avere link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Credenziali dell'account AWS e autorizzazioni di lettura/scrittura"^] per analizzare le configurazioni del database.
* Per valutare l'archiviazione di un'istanza di Microsoft SQL Server, l'istanza deve essere registrata nella Workload Factory e il tipo di archiviazione deve essere FSx per ONTAP. link:register-instance.html["Scopri come registrare un'istanza."]
* Assicurarsi di rivedere attentamente ogni suggerimento prima di selezionare per correggere un'impostazione o una configurazione. Per le impostazioni RSS e MAXDOP, si consiglia di testare le impostazioni consigliate per determinare i miglioramenti delle prestazioni prima di apportare modifiche all'ambiente di produzione.



NOTE: Il processo di correzione potrebbe causare tempi di inattività delle istanze o interruzioni del servizio. Assicuratevi di leggere attentamente la raccomandazione prima di decidere di correggere una configurazione.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella sezione Database, selezionare *Vai all'inventario dei database*.
. Nella scheda *inventario*, selezionare la scheda *istanze*.
. Selezionare *Risolvi problemi* per visualizzare i problemi di configurazione dell'istanza.
. Nella pagina Stato ben progettato dell'istanza, esaminare i risultati dell'analisi.
+
È possibile filtrare i problemi di configurazione in base a categorie, sottocategorie, stato, gravità e tag.

+
È anche possibile scaricare un report dei risultati selezionando *Esporta PDF*.

. Selezionare la freccia dell'elenco a discesa per visualizzare il suggerimento per qualsiasi configurazione. Le raccomandazioni includono le migliori pratiche, le potenziali insidie delle configurazioni non ottimizzate e considerazioni importanti. Verificare attentamente il suggerimento.
. Selezionare per *Visualizzare e correggere* i problemi di configurazione quando l'opzione è disponibile.
+
*Seleziona tutto* è l'impostazione predefinita, ma puoi selezionare risorse specifiche da correggere.

+
.. Per tutte le configurazioni, ad eccezione della pulizia del clone, rivedi i dettagli della raccomandazione per sapere cosa accadrà se scegli di risolvere il problema. Alcune operazioni di ripristino potrebbero causare tempi di inattività delle istanze o interruzioni del servizio.
.. Per la pulitura dei cloni, selezionare i database clonati (sandbox) da aggiornare o eliminare.
+
*** L'aggiornamento di un clone lo sincronizza con il relativo database di origine. L'aggiornamento è disponibile solo per i cloni creati in workload factory.
*** L'eliminazione di un clone lo rimuove in maniera permanente, libera spazio di storage e riduce i costi. Puoi eliminare i cloni creati in e all'esterno della workload Factory.




. Selezionare *continua* per risolvere il problema di configurazione.


.Risultato
Workload Factory inizia a risolvere i problemi. Selezionare la scheda *monitoraggio processo* per visualizzare lo stato dell'operazione.
