---
sidebar: sidebar 
permalink: optimize-overview.html 
keywords: database configuration issues, issues, analyze, scan, optimize, improve, database configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations, storage, compute, application, resiliency, scan, optimization, SQL Server, host, instance 
summary: Workload Factory for Databases analizza regolarmente le configurazioni di Microsoft SQL Server e Oracle per determinare se ci sono problemi. 
---
= Analisi della configurazione per ambienti di database in Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Workload Factory for Databases analizza regolarmente le configurazioni dei database per determinare se ci sono problemi con le distribuzioni di Microsoft SQL Server e Oracle su Amazon FSx for NetApp ONTAP .  Quando vengono rilevati problemi, Workload Factory ti mostra quali sono e ti spiega cosa è necessario modificare per garantire che le configurazioni del tuo database raggiungano le massime prestazioni, la massima efficienza dei costi e la conformità alle best practice.

Le funzionalità principali includono:

* Analisi quotidiana della configurazione
* Convalida automatica delle Best practice
* Consigli per un corretto dimensionamento
* Osservabilità proattiva
* Informazioni sull'azione
* Framework Advisor di AWS con architettura ottimale




== Come funziona

Workload Factory analizza quotidianamente i carichi di lavoro in esecuzione sulle implementazioni dei file system Amazon FSx for NetApp ONTAP. L'analisi fornisce stato ben architettato, approfondimenti e raccomandazioni.

Al termine dell'analisi giornaliera, le configurazioni vengono visualizzate come "ottimizzate" o "non ottimizzate" nella dashboard Well-architected per la distribuzione. Troverai il punteggio di ottimizzazione totale, i problemi di configurazione per categoria e un elenco di problemi di configurazione e raccomandazioni. Puoi esaminare le raccomandazioni relative ai problemi di configurazione. Alcuni problemi possono essere risolti automaticamente da Workload Factory, mentre altri richiedono un intervento manuale. In questo caso, Workload Factory fornisce istruzioni dettagliate per aiutarti a implementare le modifiche consigliate.

È possibile ignorare l'analisi delle configurazioni che non si applicano ai propri ambienti. In questo modo si evitano avvisi non necessari e risultati di ottimizzazione imprecisi. Quando si ignora un'analisi di configurazione specifica, Workload Factory non include la configurazione nel punteggio di ottimizzazione totale.



== Perché è importante

Workload Factory applica le best practice ad ambienti di storage, database e VMware di grandi dimensioni, combinando valutazioni continue con suggerimenti e interventi correttivi. Le correzioni automatiche applicate nella console di Workload Factory riducono gli errori umani, garantiscono una gestione uniforme e preservano prestazioni e affidabilità nelle infrastrutture di workload.



== Requisiti di analisi

Per un'analisi completa dell'ambiente del database, è necessario eseguire le seguenti operazioni:

* link:register-instance.html["Registra le tue risorse"] e assicuratevi che siano online.
* Associa un collegamento. La connettività del collegamento consente a Workload Factory di analizzare tutte le configurazioni di distribuzione del database, come la struttura di archiviazione e la resilienza.
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Scopri come associare un collegamento esistente o creare e associare un nuovo collegamento"].

* Concedi le autorizzazioni di _visualizzazione, pianificazione e analisi_ nel tuo account AWS.
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Scopri come concedere le autorizzazioni a un account AWS"^]





== Procedure consigliate e raccomandazioni per i carichi di lavoro dei database

Workload Factory fornisce una serie di best practice e raccomandazioni per la gestione di carichi di lavoro di database ben strutturati. L'analisi well-architected valuta le configurazioni e le impostazioni di Microsoft SQL Server e database Oracle relative al dimensionamento dello storage, al layout dello storage, alla configurazione dello storage, al compute, all'applicazione (SQL Server) e alla resilienza.



=== Microsoft SQL Server



==== Dimensionamento dello storage

* *Livello di storage*
+
Utilizzare il livello SSD primario per i volumi FSx for ONTAP per garantire prestazioni ottimali. Il livello del pool di capacità potrebbe ridurre le performance e aumentare la latenza. Il livello SSD primario è progettato per carichi di lavoro dalle performance elevate, mentre il livello del pool di capacità è ottimizzato per l'efficienza dei costi e potrebbe non soddisfare i requisiti di performance dei carichi di lavoro di SQL Server.

* *Spazio disponibile nel file system*
+
Mantieni una capacità del file system sufficiente, superiore alla dimensione totale del volume. Una capacità insufficiente causa problemi di performance; una capacità eccessiva spreca storage e aumenta i costi.

* *Dimensioni del disco di log*
+
Dimensionate e monitorate correttamente l'unità di log di SQL Server per prevenire rollback delle transazioni, indisponibilità del database, corruzione dei dati e problemi di performance causati da un'unità di log piena.

* *Dimensioni dell'unità TempDB*
+
Dimensionare e monitorare TempDB in modo appropriato per mantenere prestazioni ottimali e stabilità del sistema. Uno spazio TempDB insufficiente può causare rallentamenti delle query, timeout delle applicazioni e arresti anomali del sistema.





==== Layout dello storage

* *Posizionamento dei file di dati (.mdf)* e *posizionamento dei file di registro (.ldf)*
+
Posiziona i file di dati e di registro su unità separate per migliorare le performance e consentire operazioni di backup e ripristino indipendenti.

* *Posizionamento TempDB*
+
Posiziona TempDB su un'unità dedicata per evitare conflitti di I/O e migliorare le performance e la stabilità di SQL Server. In caso contrario, potresti riscontrare colli di bottiglia di I/O, query più lente e instabilità del sistema.





==== Configurazione dello storage

* *Configurazione ONTAP*
+
Abilitare thin provisioning, dimensionamento automatico e gestione dello spazio per i volumi FSx for ONTAP per ottimizzare l'efficienza dello storage e la convenienza dei costi. Configurare le policy di tiering per spostare gli snapshot meno recenti nel livello di capacità, mantenendo prestazioni elevate per i dati attivi. Per le LUN, assicurarsi che il tipo di sistema operativo corrisponda allo schema di partizionamento del sistema operativo per un corretto allineamento I/O, abilitare space reservation per prevenire errori di scrittura e abilitare space allocation per consentire space reclamation e notifiche host quando lo storage è pieno.

* *Sistema operativo*
+
Abilitare e configurare Microsoft Multipath I/O (MPIO) con impostazioni di timeout appropriate per garantire elevata disponibilità e coerenza nell'accesso ai dati per i database SQL Server su EC2 con FSx per ONTAP. MPIO fornisce percorsi ridondanti per una maggiore resilienza e performance durante i failover. Configurare la dimensione dell'unità di allocazione NTFS in modo appropriato per un utilizzo e performance del disco ottimali.





==== Calcolo

* *Dimensionamento automatico delle risorse di calcolo*
+
Dimensiona correttamente la tua istanza EC2 di SQL Server in base alle esigenze del carico di lavoro per bilanciare prestazioni ed efficienza dei costi. Se la tua istanza corrente è sottodimensionata, l'aggiornamento può migliorare la capacità di CPU, memoria e I/O. Se è sovradimensionata, il downgrade può mantenere le prestazioni riducendo i costi.

* *Patch del sistema operativo*
+
Applica le patch più recenti del sistema operativo per migliorare la sicurezza e l'affidabilità del sistema.

* *Impostazioni della scheda di rete*
+
Configura Receive Side Scaling (RSS) per distribuire l'elaborazione di rete su più processori e migliorare le performance di rete. Testa le impostazioni prima di applicarle in produzione.

* *Allineamento MTU*
+
Allinea le impostazioni della Maximum Transmission Unit (MTU) delle istanze EC2 con FSx for ONTAP per prevenire la frammentazione della rete e ottimizzare le performance di SQL Server. La correzione del disallineamento della MTU garantisce una configurazione MTU coerente su tutti i nodi e i percorsi di rete.





==== Applicazione (SQL Server)

* *Licenza*
+
La valutazione e la raccomandazione relative alla licenza di SQL Server vengono fornite a livello di host. Workload Factory considera una licenza "non ottimizzata" quando rileva che la tua infrastruttura del database non utilizza nessuna delle funzionalità della licenza software commerciale per cui stai pagando. Una licenza non ottimizzata potrebbe comportare costi inutili. Verifica l'utilizzo della tua licenza di SQL Server per assicurarti di sfruttare tutte le funzionalità per cui stai pagando.

* *Patch Microsoft SQL Server*
+
Applica le patch più recenti di SQL Server per migliorare la sicurezza, proteggere dalle vulnerabilità e migliorare l'affidabilità del sistema.

* *MAXDOP*
+
Configura MAXDOP per ottimizzare le performance delle query. I valori di 4, 8 o 16 in genere funzionano bene. Testa il tuo carico di lavoro e monitora i tipi di attesa di parallelismo come CXPACKET.





==== Affidabilità

* *Pianifica snapshot locali*
+
Pianifica snapshot regolari per backup point-in-time e ripristini rapidi in caso di cancellazioni accidentali, danneggiamento dei dati e altri problemi.

* *Configurazione backup*
+
Configura FSx for ONTAP o AWS Backup per soddisfare i requisiti di conservazione dei dati e di conformità. Evita backup ridondanti.

* *Replicazione interregionale*
+
Abilita la replica tra regioni (CRR) per migliorare la disponibilità dei dati e il disaster recovery. Utilizza CRR per proteggere dalle interruzioni regionali e garantire la business continuity.

* *Microsoft SQL Server ad alta disponibilità*
+
Assicurati che l'alta disponibilità sia configurata per SQL Server controllando che tutto lo storage condiviso sia accessibile da tutti i nodi del cluster, che le lettere di unità siano le stesse su tutti i nodi per evitare conflitti durante il failover, che il quorum sia configurato per l'integrità del cluster, che le soglie di heartbeat siano impostate per gli ambienti cloud e che i servizi di SQL Server siano configurati per l'avvio automatico e il failover.

* *Pulizia del clone*
+
Rivedere e rimuovere regolarmente i cloni obsoleti per ridurre i costi di archiviazione. I cloni vecchi e inutilizzati causano costi elevati.





=== Oracolo



==== Dimensionamento dello storage

* *Spazio disponibile nel file system*
+
Mantieni una capacità adeguata del file system per ottimizzare le performance dello storage e prevenire il peggioramento delle performance. Un margine di capacità sufficiente consente una gestione efficiente dello storage e supporta la crescita del database.

* *Spazio di swap*
+
Imposta lo spazio di swap in base alla quantità di RAM, così il sistema può gestire la pressione sulla memoria ed evitare rallentamenti o arresti anomali.





==== Layout dello storage

* *Posizionamento dei binari Oracle*
+
Posizionare i file binari di Oracle su un volume dedicato garantisce prestazioni e stabilità ottimali, riducendo la contesa di I/O. Questa separazione semplifica gli aggiornamenti del software e minimizza il rischio di modifiche accidentali o corruzione.

* *Posizionamento dei file di dati*
+
Posiziona i file di dati su un volume dedicato o insieme ai file di controllo per isolare le operazioni di I/O casuali e migliorare le performance. Questa separazione consente configurazioni di snapshot personalizzate, politiche di tiering e meccanismi di efficienza per ottimizzare le performance e i costi.

* *Posizionamento dei file di controllo*
+
Archivia copie dei file di controllo su volumi o dischi diversi per evitare un single point of failure e aggiungere ridondanza. Posiziona i file di controllo su un volume dedicato oppure condividili con i redo log o i data file, ma non posizionarli su volumi suddivisi in livelli per storage a oggetti a causa dei requisiti di performance.

* *Posizionamento dei redo log*
+
Posiziona i redo log su un volume dedicato o condividili in modo appropriato con i file temporanei o di controllo per isolare le operazioni di I/O ad alta scrittura e migliorare le performance. Archivia ogni copia del redo log su un volume separato per la ridondanza. Non posizionare i redo log su snapshot di volume o su volumi suddivisi in livelli per lo storage a oggetti perché vengono aggiornati frequentemente.

* *Incarico temporaneo*
+
Posiziona i file temporanei su un volume dedicato o condividili in modo appropriato con i file di redo o di controllo per isolare le operazioni di I/O ad alto numero di scritture e migliorare le performance. Ogni copia temporanea multiplexata dovrebbe risiedere su un volume separato per la ridondanza. I file temporanei non devono essere posizionati su snapshot di volume o su volumi suddivisi in livelli verso storage a oggetti a causa dei loro frequenti aggiornamenti.

* *Posizionamento dell'archivio*
+
Posizionare i file di log di archivio su un volume dedicato per migliorare le performance e i processi di ripristino, evitando che elevate richieste di I/O interferiscano con altre operazioni del database.

* *Configurazioni solo ASM: LUN del gruppo di dischi dati ASM, LUN del gruppo di dischi dei log ASM e LUN del gruppo di dischi di archiviazione ASM*
+
Distribuisci le LUN tra i gruppi di dischi dati, redo log e archive log di Automatic Storage Management (ASM) per prestazioni ottimali e ridondanza.





==== Configurazione dello storage

* *ONTAP*
+
Ottimizza la configurazione di FSx for ONTAP per i database Oracle abilitando thin provisioning, dimensionamento automatico e gestione dello spazio per i volumi. Configura policy di snapshot e strategie di tiering appropriate per bilanciare performance e costi. Per le LUN, assicurati che l'allineamento del tipo di sistema operativo, space reservation e le impostazioni di allocazione dello spazio siano corretti per prevenire errori di scrittura e abilitare space reclamation automatica.

* *Sistema operativo*
+
Configurare le impostazioni del sistema operativo per prestazioni ottimali del database Oracle, inclusa la messa a punto dei parametri del kernel per i carichi di lavoro del database e la configurazione appropriata delle impostazioni NFS o dNFS per l'accesso al file system di rete.





==== Calcolo

* *Patch del sistema operativo*
+
Applica regolarmente le patch del sistema operativo per garantire sicurezza, stabilità e miglioramenti delle performance per il tuo ambiente database Oracle.



.Cosa succederà
link:optimize-configurations.html["Implementare configurazioni di database ben progettate"]
