---
sidebar: sidebar 
permalink: postpone-analysis.html 
keywords: postpone configuration analysis, dismiss configuration analysis, postpone, dismiss, stop, optimization, Microsoft SQL Server, host, instance, FSx for ONTAP 
summary: 'Rinviare o respingere l"analisi di configurazioni specifiche del database che non si applicano all"ambiente di database per evitare avvisi non necessari e risultati di ottimizzazione imprecisi.' 
---
= Rinviare o respingere l'analisi delle configurazioni di database
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Rinviare o respingere l'analisi di configurazioni specifiche del database che non si applicano all'ambiente di database per evitare avvisi non necessari e risultati di ottimizzazione imprecisi. È possibile riattivare in qualsiasi momento un'analisi della configurazione posticipata o ignorata.

.A proposito di questa attività
I requisiti delle applicazioni per le configurazioni di database variano. Workload Factory offre due opzioni per ignorare l'analisi di specifiche configurazioni di database, in modo da poter monitorare solo i problemi rilevanti e ottenere una visione accurata dello stato delle configurazioni pertinenti. Quando un'analisi di configurazione specifica viene rinviata o chiusa, la configurazione non viene inclusa nel punteggio di ottimizzazione totale.

È possibile rimandare, ignorare e riattivare l'analisi della configurazione a livello di configurazione e a livello di istanza di SQL Server.

* *Rimandare per 30 giorni*: Posticipando l'analisi si fermerà l'analisi per 30 giorni. Dopo 30 giorni, l'analisi verrà riavviata automaticamente.
* *Smissing*: L'eliminazione dell'analisi rinvia l'analisi a tempo indeterminato. Se necessario, è possibile riavviare l'analisi.


È possibile rimandare o chiudere le seguenti configurazioni per le istanze di Microsoft SQL Server:

* Dimensionamento dello storage: Include Tier di storage, capacità aggiuntiva del file system, dimensioni dei dischi di log e dimensioni dei dischi TempDB
* Layout dello storage: Comprende posizionamento dei file di dati degli utenti, posizionamento dei file di log e posizionamento di TempDB
* Configurazione dello storage: Comprende gestione della capacità, thin provisioning, policy di tiering, snapshot, stato i/o multi-path, policy, sessioni e altro ancora
* Calcolo: Include il dimensionamento corretto, le patch del sistema operativo e le impostazioni della scheda di rete come Receive Side Scaling (RSS) e TCP offload
* Applicazioni: Include le licenze di Microsoft SQL Server, la patch di Microsoft SQL Server e le impostazioni MAXDOP
* Resilienza: Include snapshot locali, FSX per i backup ONTAP e replica tra aree (CRR)
* Cloni


Le seguenti istruzioni descrivono come rinviare, ignorare o riattivare un'analisi a livello di configurazione. Per completare le seguenti attività per istanze SQL Server specifiche, avviare la scheda *Dashboard*.

[role="tabbed-block"]
====
.Posticipa
--
Rinviare per 30 giorni l'interruzione di un'analisi di configurazione. Dopo 30 giorni, l'analisi verrà riavviata automaticamente.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella sezione Database, selezionare *Vai all'inventario dei database*.
. Nella scheda *inventario*, scorrere verso il basso fino alla configurazione da rinviare, selezionare il menu a tre punti, quindi selezionare *rinvia per 30 giorni*.
. Selezionare *continua*.


.Risultato
L'analisi della configurazione si interrompe per 30 giorni.

--
.Ignora
--
Ignorare per interrompere un'analisi di configurazione a tempo indeterminato. È possibile riavviare l'analisi quando necessario.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella sezione Database, selezionare *Vai all'inventario dei database*.
. Nella scheda *inventario*, scorrere fino alla configurazione da chiudere, selezionare il menu a tre punti, quindi selezionare *Ignora*.
. Selezionare *continua*.


.Risultato
L'analisi della configurazione si interrompe.

--
.Riattiva
--
Riattivare in qualsiasi momento un'analisi di configurazione posticipata o ignorata.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella sezione Database, selezionare *Vai all'inventario dei database*.
. Nella scheda *inventario*, scorrere verso il basso fino alla configurazione da riattivare, selezionare il menu a tre punti, quindi selezionare *Riattiva*.
. Selezionare *continua*.


.Risultato
L'analisi della configurazione viene riattivata e viene eseguita quotidianamente.

--
====