---
settings:
  name: Database workloads
  platform: cloud
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentazione relativa ai carichi di lavoro dei database
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/whats-new.html"
    - title: Limitazioni note
      url: "/known-limitations.html"
  - title: Inizia subito
    entries:
    - title: Scopri la fabbrica di workload per i database
      url: "/learn-databases.html"
    - title: Avvio rapido
      url: "/quick-start-databases.html"
  - title: Utilizzo di carichi di lavoro del database
    entries:
    - title: Scopri i risparmi
      url: "/explore-savings.html"
    - title: Creare un nuovo server di database
      entries:
      - title: Creare Microsoft SQL Server
        url: "/create-database-server.html"
      - title: Creare PostgreSQL Server
        url: "/create-postgresql-server.html"
    - title: Gestisci le istanze
      entries:
      - title: Gestione delle istanze
        url: manage-instance.html
      - title: Registra un'istanza
        url: "/register-instance.html"
      - title: Visualizzare i database
        url: "/view-databases.html"
      - title: Creare un database
        url: "/create-database.html"
      - title: Creare un clone sandbox
        url: "/create-sandbox-clone.html"
    - title: Automatizza con Codebox
      url: "/automate-codebox.html"
  - title: Amministrare e monitorare
    entries:
    - title: Monitorare i database
      url: "/monitor-databases.html"
    - title: Implementare le migliori pratiche di configurazione
      entries:
      - title: Analisi della configurazione per database
        url: "/optimize-overview.html"
      - title: Implementare configurazioni di database ben progettate
        url: "/optimize-configurations.html"
      - title: Posticipare l'analisi della configurazione
        url: "/postpone-analysis.html"
    - title: Gestire un Microsoft SQL Server
      url: "/manage-server.html"
    - title: Gestire i cloni
      entries:
      - title: Verificare l'integrità di un clone sandbox
        url: "/check-clone-integrity.html"
      - title: Ripristina un clone sandbox
        url: "/revert-clone.html"
      - title: Aggiornare un clone sandbox
        url: "/refresh-clone.html"
      - title: Connettersi alla pipeline ci/CD
        url: "/connect-clone-cicd.html"
      - title: Visualizzare le informazioni sulla connessione clone
        url: "/view-clone-connection.html"
      - title: Dividere un clone sandbox
        url: "/split-clone.html"
      - title: Eliminare un clone sandbox
        url: "/delete-clone.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/support-registration.html"
    - title: Richiedi assistenza
      url: "/get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: BlueXP workload factory
  repo: workload-family
