---
settings:
  name: Database workloads
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentazione relativa ai carichi di lavoro dei database
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/whats-new.html"
    - title: Limitazioni note
      url: "/known-limitations.html"
  - title: Inizia subito
    entries:
    - title: Scopri di più su Workload Factory per database
      url: "/learn-databases.html"
    - title: Avvio rapido
      url: "/quick-start-databases.html"
  - title: Usa Workload Factory per i carichi di lavoro database
    entries:
    - title: Scopri i risparmi
      url: "/explore-savings.html"
    - title: Crea risorse di database
      entries:
      - title: Creare Microsoft SQL Server
        url: "/create-database-server.html"
      - title: Creare PostgreSQL Server
        url: "/create-postgresql-server.html"
      - title: Creare un database
        url: "/create-database.html"
      - title: Creare un clone sandbox
        url: "/create-sandbox-clone.html"
    - title: Gestisci le risorse
      entries:
      - title: Gestione delle risorse
        url: "/manage-instance.html"
      - title: Registra le risorse
        url: "/register-instance.html"
      - title: Gestire i cloni
        url: "/manage-clones.html"
      - title: Annullare la registrazione delle risorse
        url: "/deregister-instance.html"
  - title: Proteggi, monitora e ottimizza le risorse del database
    entries:
    - title: Analizza i registri degli errori
      url: "/analyze-error-logs.html"
    - title: Implementare le migliori pratiche di configurazione
      entries:
      - title: Analisi della configurazione per database
        url: "/optimize-overview.html"
      - title: Implementare configurazioni di database ben progettate
        url: "/optimize-configurations.html"
    - title: Monitorare i lavori del database
      url: "/monitor-databases.html"
    - title: Proteggere i carichi di lavoro di Microsoft SQL Server
      url: "/protect-sql-server.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/support-registration.html"
    - title: Richiedi assistenza
      url: "/get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
