---
sidebar: sidebar 
permalink: protect-sql-server.html 
keywords: protect, server, Microsoft SQL Server, SQL Server, protect instance, protect database 
summary: Proteggere le istanze e i database di Microsoft SQL Server. 
---
= Proteggere i carichi di lavoro di Microsoft SQL Server
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Proteggi i dati delle tue applicazioni Microsoft SQL Server utilizzando il BlueXP backup and recovery dalla console Workload Factory. Grazie a questa integrazione, è possibile raggiungere i seguenti obiettivi di protezione: eseguire il backup dei carichi di lavoro con snapshot locali sullo storage primario locale Amazon FSx for NetApp ONTAP (FSx for ONTAP) e replicare i carichi di lavoro sullo storage secondario FSx for ONTAP .



== A proposito di questa attività

Workload Factory automatizza la scoperta delle risorse, la convalida dei prerequisiti e la configurazione e l'installazione del plug-in per Microsoft SQL Server, per preparare i carichi di lavoro alla protezione con il BlueXP backup and recovery. Il plug-in è un componente lato host di NetApp Software che consente di proteggere i carichi di lavoro di Microsoft SQL Server.

Il BlueXP backup and recovery sfruttano la tecnologia di replicazione dei dati NetApp SnapMirror per garantire che tutti i backup siano completamente sincronizzati creando copie snapshot e trasferendole nelle posizioni di backup.

Per i dettagli sulla protezione con BlueXP backup and recovery, fare riferimento alink:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-mssql-protect-overview.html["Panoramica sulla protezione dei carichi di lavoro Microsoft SQL con BlueXP backup and recovery"^] .



== Prima di iniziare

Per proteggere i carichi di lavoro di Microsoft SQL Server con il BlueXP backup and recovery, è necessario soddisfare i seguenti requisiti.

* Assicurati che il tuo ambiente soddisfilink:https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-start-prereq.html#microsoft-sql-server-workload-requirements["requisiti BlueXP backup and recovery per SQL Server"^] .
* link:https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-start-prereq.html#in-bluexp["Requisiti completi di BlueXP"^]inclusa la configurazione di BlueXP, ruoli IAM e un connettore BlueXP .
+
Se si dispone dell'accesso come amministratore dell'organizzazione all'account BlueXP , `backup and recovery super admin` il ruolo viene assegnato automaticamente quando<<Preparati alla protezione con il BlueXP backup and recovery,preparati alla protezione con il BlueXP backup and recovery>> .

+
** Imposta la risoluzione host sul connettore
+
Per scoprire i database, è necessario impostare la risoluzione host sul connettore.  Sul dispositivo ospitato, aggiungere la mappatura dell'indirizzo IP al nome host nel `/etc/hosts` file.



* link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-start-licensing.html["Impostare la licenza per il BlueXP backup and recovery"^]
* Nella fabbrica dei carichi di lavoro per i database, assicurati di registrare le istanze utilizzando le credenziali di Windows.  Per fornire le credenziali di Windows, andare alla scheda Istanze dall'inventario.  Identifica l'istanza, seleziona *Gestisci istanze*, quindi seleziona *Dashboard istanza*.  Dal dashboard dell'istanza, seleziona il menu a tre punti, quindi seleziona *Aggiorna password Microsoft SQL Server*.  Aggiorna la password utilizzando l'autenticazione di Windows.




== Preparati alla protezione con il BlueXP backup and recovery

Completa il processo di preparazione per proteggere le tue risorse di Microsoft SQL Server con il BlueXP backup and recovery.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella sezione Database, selezionare *Vai all'inventario dei database*.
. In Database, selezionare la scheda *inventario*.
. Filtra il *Tipo di motore* su *Microsoft SQL Server*.
. Selezionare *Proteggi* dal menu per l'istanza da proteggere.
. Selezionare il *Connettore* in cui si desidera registrare e proteggere il carico di lavoro.
. Per preparare la protezione dei dati, Workload Factory registra automaticamente le risorse di SQL Server in BlueXP backup and recovery, configura e installa il plug-in per Microsoft SQL Server e individua le risorse che soddisfano i prerequisiti per la protezione dell'istanza di SQL Server.  Selezionare *Avvia* per iniziare il processo.
. Dopo aver soddisfatto i prerequisiti, seleziona *Reindirizza* per accedere BlueXP backup and recovery.


.Cosa succederà
Da BlueXP backup and recovery, crea un criterio per proteggere la tua istanza e i tuoi database di Microsoft SQL Server.

link:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-policies-create.html["Scopri come creare un criterio per proteggere l'istanza e i database di Microsoft SQL Server"^] .

Per informazioni correlate, fare riferimento alink:https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-mssql-protect-overview.html["Documentazione BlueXP backup and recovery"^] per la gestione dei carichi di lavoro di Microsoft SQL Server.
