---
sidebar: sidebar 
permalink: refresh-clone.html 
keywords: refresh clone, sync, update, database, Microsoft SQL 
summary: Fare un refresh di un clone della sandbox in workload Factory per i database. 
---
= Fare un refresh di un clone della sandbox in workload Factory per i database
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Aggiornare un clone del database in modo che sia equivalente al database di origine al momento corrente o a un punto temporale precedente.

.A proposito di questa attività
L'aggiornamento di un clone aggiorna il clone nel database di origine al momento corrente o in uno snapshot del database di origine acquisito in un point-in-time precedente. Tutte le modifiche apportate al clone sandbox verranno eliminate.

.Prima di iniziare
Un aggiornamento è possibile solo quando il database di origine è attivo.

Per aggiornare un clone del database da uno snapshot, il database di origine deve avere almeno uno snapshot per l'operazione.

.Fasi
. Accedere a link:https://console.workloads.netapp.com["Console di workload Factory"^].
. Nella sezione Database, selezionare *Vai a inventario database*.
. In Database, selezionare la scheda *Sandbox*.
. Nella scheda Sandboxes, fare clic sul menu dei tre punti del clone sandbox che si desidera aggiornare.
. Selezionare *Aggiorna*.
. Nella finestra di dialogo Aggiorna, selezionare una delle seguenti opzioni:
+
.. *Aggiorna all'ora corrente*
.. *Aggiorna al punto nel tempo*
+
Per questa opzione, selezionare l'istantanea del database dal menu a discesa per aggiornarla a.



. Fare clic su *Aggiorna*.

