---
sidebar: sidebar 
permalink: revert-clone.html 
keywords: re-baseline, revert clone, database, Microsoft SQL 
summary: 'Ripristina un clone di database (sandbox) alla sua versione originale al momento della creazione in NetApp Workload Factory for Databases.' 
---
= Ripristina un clone del database in NetApp Workload Factory per database
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Ripristina un clone di database (sandbox) alla sua versione originale al momento della creazione in NetApp Workload Factory for Databases.

.A proposito di questa attività
Quando si clona un database, il clone al momento della creazione è un clone _di base_.  I dati nel database clonato sono gli stessi del database di origine al momento della creazione.  Poiché i dati in un clone di database cambiano nel tempo, potrebbe essere opportuno ripristinare i dati allo stato di base al momento della creazione del clone.  Questa operazione è chiamata ri-baselining di un clone.  Rieseguire la baseline di un clone anziché crearne uno nuovo consente di risparmiare spazio; tuttavia, tutte le modifiche apportate al clone del database verranno eliminate.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella sezione Database, selezionare *Vai all'inventario dei database*.
. Dal menu Database, selezionare *Sandbox*.
. In Sandbox, seleziona il menu azioni del clone del database che vuoi ripristinare.
. Selezionare *Rebaseline*.
. Nella finestra di dialogo Re-baseline, selezionare *Re-baseline*.

