---
sidebar: sidebar 
permalink: revert-clone.html 
keywords: re-baseline, revert clone, database, Microsoft SQL 
summary: Ripristina un clone sandbox in workload Factory per i database. 
---
= Ripristina un clone sandbox in workload Factory per i database
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Ripristinare la versione originale di un clone del database al momento della creazione.

.A proposito di questa attività
Quando si clona un database, il clone al momento della creazione è un clone _baseline_. I dati nel database clonato corrispondono a quelli del database di origine al momento della creazione. Quando i dati di un clone di database sandbox cambiano nel tempo, è possibile ripristinare i dati di base alla prima creazione del clone. Questa operazione è chiamata re-baselining di un clone. Ridefinire il valore di base di un clone anziché crearne uno nuovo consente di risparmiare spazio, tuttavia qualsiasi modifica apportata al clone sandbox verrà eliminata.

.Fasi
. Accedere a link:https://console.workloads.netapp.com["Console di workload Factory"^].
. Nella sezione Database, selezionare *Vai a inventario database*.
. In Database, selezionare la scheda *Sandbox*.
. Nella scheda Sandbox, fare clic sul menu dei tre punti del clone sandbox che si desidera ripristinare.
. Selezionare *Rebaseline*.
. Nella finestra di dialogo Re-baseline, fare clic su *Re-baseline*.

