---
sidebar: sidebar 
permalink: split-clone.html 
keywords: split, clone, source, new database 
summary: Dividere un clone del database dal database di origine per creare un nuovo database in NetApp Workload Factory for Databases. 
---
= Dividere un clone del database dal database di origine
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
In NetApp Workload Factory for Databases, la suddivisione di un clone di database dal suo database di origine crea un nuovo database che consumerà una certa quantità di capacità di archiviazione.  Il clone verrà eliminato al termine della suddivisione e il nuovo database apparirà nell'inventario.

.Prima di iniziare
Considerare la capacità di storage necessaria per il nuovo database. Se necessario, link:https://docs.netapp.com/us-en/workload-fsx-ontap/increase-file-system-capacity.html["aumentare la capacità del file system"^] per il file system FSX for ONTAP prima di iniziare.

.Fasi
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella sezione Database, selezionare *Vai all'inventario dei database*.
. Dal menu Database, selezionare *Sandbox*.
. In Sandbox, seleziona il menu azioni del clone del database che vuoi dividere.
. Selezionare *Dividi*.
. Nella finestra di dialogo Dividi, seleziona *Dividi*.

