---
sidebar: sidebar 
permalink: view-databases.html 
keywords:  
summary: 'Per ottenere un riepilogo delle risorse del database nella Workload Factory, visualizza tutti i database nell"inventario. Puoi anche visualizzare i database per singola istanza registrata.' 
---
= Visualizza i database nella fabbrica dei carichi di lavoro per i database
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Per ottenere un riepilogo delle risorse del database nella Workload Factory, visualizza tutti i database nell'inventario. Puoi anche visualizzare i database per singola istanza registrata.

.Prima di iniziare
* Le istanze che contengono risorse di database devono disporre di FSx per l'archiviazione del file system ONTAP.
* Per visualizzare i database è necessario registrare le istanze nella fabbrica dei carichi di lavoro. Scopri come link:register-instance.html["registrare un'istanza"] .


.Fasi
[role="tabbed-block"]
====
.Visualizza i database per una singola istanza
--
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella sezione Database, selezionare *Vai all'inventario dei database*.
. In Database, selezionare la scheda *inventario*.
. Fare clic sul menu a tre punti dell'istanza e quindi selezionare *Visualizza database*.


I database vengono visualizzati per la singola istanza nella scheda Database.

--
.Visualizza i database per tutte le istanze
--
. Accedere utilizzando uno dei link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["esperienze di console"^].
. Nella sezione Database, selezionare *Vai all'inventario dei database*.
. In Database, selezionare la scheda *inventario*.
. Selezionare la scheda *Database*.
+
I database vengono visualizzati per tutte le istanze registrate.



--
====